(function(g){var window=this;'use strict';var v4=function(a){a.ma("cardstatechange",a.lk()&&a.zo()?1:0)},w4=function(a,b){var c=g.Ia(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},jdb=function(a){var b=g.Tm(a);
a=g.Wm(a);return new g.Im(b.x,b.y,a.width,a.height)},kdb=function(a){return Math.pow(a,3)},ldb=function(a){return 3*a*a-2*a*a*a},z4=function(a){a=g.Na(a);
delete x4[a];g.hd(x4)&&y4&&y4.stop()},ndb=function(){y4||(y4=new g.Jp(function(){mdb()},20));
var a=y4;a.isActive()||a.start()},mdb=function(){var a=g.Ra();
g.Tc(x4,function(b){odb(b,a)});
g.hd(x4)||ndb()},A4=function(a,b,c,d){g.cq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.J=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.I=0;this.C=null},odb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.I=1E3/(b-a.C);a.C=b;pdb(a,a.progress);1==a.progress?(a.j=0,z4(a),a.onFinish(),a.Hq()):a.hd()&&a.eJ()},pdb=function(a,b){"function"===typeof a.D&&(b=a.D(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.J[c]-a.u[c])*b+a.u[c]},qdb=function(a,b){g.ib.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.I;this.state=b.j},B4=function(a,b,c,d,e){A4.call(this,b,c,d,e);
this.element=a},rdb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
B4.call(this,a,b,c,d,e)},sdb=function(a){g.C.call(this);
this.u=a||window;this.j=[]},C4=function(a){return a.baseUrl||null},D4=function(a,b){return g.Vn(g.hi(a,b),function(c){return!!c})},tdb=function(a,b,c){function d(Q){var X=Q.hovercardButton;
if(!X)return null;X=X.subscribeButtonRenderer;if(!X)return null;var O=f(X.unsubscribedButtonText),la=f(X.subscribedButtonText);if(X.subscribed){var qa=f(X.subscriberCountWithUnsubscribeText);var Ma=f(X.subscriberCountText)}else qa=f(X.subscriberCountText),Ma=f(X.subscriberCountWithSubscribeText);var Qa=null;if(Q.signinEndpoint){Qa=w4(Q,"signinEndpoint","webNavigationEndpointData","url");if(!Qa){var ua,bb;Qa=null==(bb=g.K(null==(ua=X.signInEndpoint)?void 0:ua.commandMetadata,g.q3))?void 0:bb.url}if(!Qa)return null}return O&&
(la||Qa)?{subscribed:X.subscribed,subscribeText:O,subscribeCount:qa,unsubscribeText:la,unsubscribeCount:Ma,enabled:X.enabled,signinUrl:Qa,classic:Q.useClassicSubscribeButton}:null}
function e(Q){if(Q){var X=[],O=Q.videoId;O&&X.push("v="+O);(O=Q.playlistId)&&X.push("list="+O);(Q=Q.startTimeSeconds)&&X.push("t="+Q);return"/watch?"+X.join("&")}}
function f(Q){if(!Q)return null;var X=Q.simpleText;return X?X:Q.runs?g.hi(Q.runs,function(O){return O.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,u=null,x=null,z=!1,B=null,F=null,G=null,E=null,L=null,P=null;if("VIDEO"===h)g.K(l,g.pM)?m=g.K(l,g.pM).url:(P=g.K(l,g.oM),m=e(P)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.K(l,g.pM)?m=g.K(l,g.pM).url:(P=g.K(l,g.oM),m=e(P)),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"===
h){if(z=w4(l,"browseEndpoint","browseId"))x=z,m="/channel/"+x;n=!1;q="new";(z=!!b.isSubscribe)?B=d(b):F=f(b.subscribersText)}else"WEBSITE"===h?((G=w4(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(E=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=w4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=w4(b,"title","accessibility","accessibilityData","label");var U=b.endpoint?b.endpoint.clickTrackingParams:null,
aa="";if(b.metadata){var W=f(b.metadata);W&&(aa=W)}return{id:"element-"+c,type:h,title:f(b.title),metadata:aa,callToAction:f(b.callToAction),iT:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,xC:p,playlistLength:u,channelId:x,subscribeButton:B,subscribersText:F,isSubscribe:z,Kt:m||null,H4:n,sessionData:U?{itct:U}:null,I9:q,WA:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:D4(b.impressionUrls||[],C4),w4:D4(b.hovercardShowUrls||[],C4),clickUrls:D4(l.loggingUrls||[],C4),visualElement:g.BE(b.trackingParams),productPrice:E,additionalFeesText:L,watchEndpoint:P||null}},udb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:D4(a.impressionUrls||[],C4),elements:D4(a.elements||[],function(d,e){return tdb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.BE(a.trackingParams));return c},vdb=function(a){g.AT.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.Y=!0;this.I=0;a=a.T();this.V=g.lK(a)||"profilepage"===a.Ea;this.events=new g.cI(this);g.D(this,this.events);this.events.S(this.player,g.ZD("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.$D("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.Cb);this.events.S(window,"focus",this.q8);this.load();var b=g.qf("STYLE");(g.Xe("HEAD")[0]||document.body).appendChild(b);g.ab(this,
function(){g.xf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},wdb=function(a){return a.player.getVideoData().D?"current":a.V?"new":"current"},E4=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},xdb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=udb(f,wdb(a))));F4(a,f)},
urlParams:{v:c},withCredentials:!0};a.V&&(c.urlParams.ptype="embedded");var d=b.kx;d&&(c.postParams={ad_tracking:d});if(b=g.$za(b))if(b=g.de(b),b=g.be(b))a.B=g.Ly(b,c)},F4=function(a,b,c){c=void 0===c?!0:c;
a.player.If("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.t(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&ydb(a);c=[];d=new g.XD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().u||(a.u=new g.T({G:"div",N:"ytp-ce-shadow"}),g.KS(a.player,a.u.element,4),a.C=new g.OQ(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=zdb(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.KS(a.player,f.element,4);var h=new g.XD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Adb(a,f,e)}else g.DD(new g.fA("buildEndscreenElement null",
e))}a.player.ye(c);a.Cb()}},ydb=function(a){var b=g.EE(),c=g.FE();
c&&b&&a.endscreen.visualElement&&g.qy(g.bP)(void 0,c,b,a.endscreen.visualElement)},zdb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",Ia:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.WA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-covering-image",X:G4(b)},{G:"div",N:"ytp-ce-covering-shadow-top"},{G:"a",N:"ytp-ce-covering-overlay",X:{href:H4(a,b.Kt),tabindex:"-1"},W:[{G:"div",Ia:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.gq(b.title||"")},qa:b.title},{G:"div",N:b.xC?"ytp-ce-live-video-duration":"ytp-ce-video-duration",qa:b.videoDuration||
void 0}]}]};c=new g.T(a);break;case "PLAYLIST":a={G:"div",Ia:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.WA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-covering-image",X:G4(b)},{G:"div",N:"ytp-ce-covering-shadow-top"},{G:"a",N:"ytp-ce-covering-overlay",X:{href:H4(a,b.Kt),tabindex:"-1"},W:[{G:"div",Ia:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.gq(b.title||"")},qa:b.title},{G:"div",N:"ytp-ce-playlist-count",W:[{G:"div",N:"ytp-ce-playlist-icon"},
{G:"div",N:"ytp-ce-playlist-count-text",qa:b.playlistLength||void 0}]}]}]};c=new g.T(a);break;case "CHANNEL":c={G:"div",Ia:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.WA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",W:[{G:"div",
N:"ytp-ce-expanding-overlay-body",W:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"a",Ia:["ytp-ce-channel-title","ytp-ce-link"],X:{href:H4(a,b.Kt),target:"_blank",tabindex:"-1",dir:g.gq(b.title||"")},qa:b.title},b.subscribeButton?{G:"div",N:"ytp-ce-subscribe-container",W:[{G:"div",N:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",N:"ytp-ce-channel-subscribers-text",qa:b.subscribersText}:"",b.metadata?{G:"div",Ia:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
qa:b.metadata}:""]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:G4(b)}]};c=new g.T(c);var d=g.Ye(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Rp(d,"ytp-ce-subscribe-button");if(a.player.T().u){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.lU(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={G:"div",Ia:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.WA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",W:[{G:"div",N:"ytp-ce-expanding-overlay-body",
W:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",N:"ytp-ce-website-title",X:{dir:g.gq(b.title||"")},qa:b.title},{G:"div",N:"ytp-ce-website-metadata",qa:b.metadata},{G:"a",Ia:["ytp-ce-website-goto","ytp-ce-link"],X:{href:H4(a,b.Kt),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:G4(b)},{G:"div",N:"ytp-ce-expanding-icon",X:Bdb(b.iconUrl)}]};c=new g.T(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",N:"ytp-ce-merchandise-price-container",
W:[{G:"div",N:"ytp-ce-merchandise-price",qa:b.productPrice}]},b.additionalFeesText&&c.W.push({G:"div",N:"ytp-ce-merchandise-additional-fees",qa:b.additionalFeesText})),a={G:"div",Ia:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.WA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",
W:[{G:"div",N:"ytp-ce-expanding-overlay-body",W:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",N:"ytp-ce-merchandise-title",X:{dir:g.gq(b.title||"")},qa:b.title},c,{G:"div",N:"ytp-ce-merchandise-metadata",qa:b.metadata},{G:"a",Ia:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:H4(a,b.Kt),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:G4(b)},{G:"div",N:"ytp-ce-merchandise-invideo-cta-container",W:[{G:"div",N:"ytp-ce-merchandise-invideo-cta",
qa:b.callToAction||void 0}]}]},c=new g.T(a)}b.isPlaceholder&&g.Rp(c.element,"ytp-ce-placeholder");return c},G4=function(a){if(a.iT)var b=a.iT.thumbnails;
return Bdb(b?b[b.length-1].url:null)},Bdb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Adb=function(a,b,c){function d(m){m&&(b.Qa("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.Rp(b.element,"ytp-ce-force-expand"),I4(a,c.id,!0)):(g.Tp(b.element,"ytp-ce-force-expand"),g.Tp(b.element,"ytp-ce-element-hover"),I4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Qa("mouseenter",function(){Cdb(a,b,c)});
b.Qa("mouseleave",function(){Ddb(a,b,c)});
a.player.T().u||b.Qa("click",function(){g.Rp(b.element,"ytp-ce-element-hover")});
b.Qa("click",function(m){Edb(a,c,m)});
b.Qa("keypress",function(m){Edb(a,c,m)});
b.Qa("focus",function(){Cdb(a,b,c)});
b.Qa("blur",function(){Ddb(a,b,c)});
b.Qa("touchstart",function(){Cdb(a,b,c)});
var l=g.$e("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){g.yO?m.stopPropagation():(m=m||window.event,m.cancelBubble=!0,m.stopPropagation&&m.stopPropagation());g.Tp(b.element,"ytp-ce-element-hover");g.Tp(b.element,"ytp-ce-force-expand")});
b.Qa("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.$e("ytp-sb-subscribe",b.element));d(g.$e("ytp-sb-unsubscribe",b.element));b.Qa("focus",f);b.Qa("blur",h)},Edb=function(a,b,c){if(b.Kt&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Qp(d,"ytp-ce-element");){g.Qp(d,"subscribe-label")&&Fdb(a,b);
if(g.Qp(d,"ytp-ce-channel-subscribe"))return;d=g.yf(d)}if(!d||g.Qp(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Ddb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.I9)Fdb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.de(H4(a,b.Kt)),g.IN(g.be(c),void 0,b.sessionData);else{var e=g.DK(a.player.T())||a.player.getVideoData().D,f=function(){var h=H4(a,b.Kt),l=b.sessionData,m=b.watchEndpoint,n=g.wy(h);e&&n&&(n.v||n.list)?a.player.Ln(n.v,
l,n.list,!1,void 0,m||void 0):g.GN(h,l)};
Fdb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},H4=function(a,b){a=a.player.T();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.MK(a)+b}else return"";return b},Cdb=function(a,b,c){g.Qp(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Rp(b.element,"ytp-ce-element-hover"):a.player.T().u?(new g.Jp(function(){g.Rp(b.element,"ytp-ce-element-hover")},200)).start():g.Rp(b.element,"ytp-ce-element-hover"),J4(a,c.w4),I4(a,c.id,!0))},Ddb=function(a,b,c){g.Tp(b.element,"ytp-ce-element-hover");
g.Tp(b.element,"ytp-ce-force-expand");I4(a,c.id,!1)},I4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.t(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Vp(a.j[e].element,"ytp-ce-element-shadow-show",c)},J4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||E4(a))c&&c();else{b=Gdb(a,b);var e=0,f=!1,h=new g.Jp(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.ZB(b[a],d)}},Fdb=function(a,b,c){J4(a,b.clickUrls,c);
(a=g.FE())&&b.H4&&g.kP(a,b.visualElement)},Gdb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Hdb(b[d],c));return a},Hdb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Idb=function(a){return"string"===typeof a?a:""},K4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Jdb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},L4=function(a){return a.value?a.value:null},M4=function(a){if(!a)return null;
var b=g.de(Idb(a.value));b=g.be(b);if(!b)return null;var c=K4(a.target,Kdb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Jdb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Ldb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Odb=function(a){if(!a)return null;
var b=K4(a.type,Mdb),c=K4(a.trigger,Ndb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=M4(a?a:null);return b?new Ldb(b,c,a):null},Pdb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Qdb=function(a,b){return g.nb(a.action,b)},Rdb=function(a,b){this.context=a;
this.j=b},Sdb=function(a){return a.customMessage?N4("div","iv-card-message",a.customMessage):""},O4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",N:"iv-card-image",X:{style:a},W:c}},Tdb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.t(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(N4("li","",c.value));return{G:"ul",N:"iv-card-meta-info",W:b}},N4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.gq(c);return{G:a,X:b,qa:c}},Udb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.gB&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.gB+");");c.dir=g.gq(a.customMessage);var d=[{G:"span",qa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",N:"iv-card-link-icon"}));return{G:"div",Ia:b,X:c,W:d}},P4=function(a,b,c,d){if(d){b=g.t(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Qi.click,5)}},Vdb=function(a,b){this.merchant=a;
this.price=b},Wdb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Xdb=function(a,b){return b?b:Wdb(a)?"current":"new"},Q4=function(a,b){g.C.call(this);
var c=this;this.element=a;this.context=b;this.tb=!1;this.Za=new Map;this.gb=new Map;this.context.F.addEventListener(g.ZD("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)});
this.context.F.addEventListener(g.$D("annotations_module"),function(d){(d=c.gb.get(d))&&d.apply(c)})},R4=function(a,b,c,d,e,f,h){a.context.j.Qa(b,"click",function(l){a.fJ(c,d,e,f||[],h||0,l)});
a.context.j.Qa(b,"touchstart",function(){a.tb=!1});
a.context.j.Qa(b,"touchmove",function(){a.tb=!0})},Ydb=function(a){var b;
return(null==(b=g.K(a,g.pM))?0:b.url)?g.K(a,g.pM).url:(a=g.K(a,g.oM))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},S4=function(a,b,c){return{GU:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
cY:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
nI:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Zdb=function(a,b,c){Q4.call(this,b,c);
var d=this;this.F=a;this.eventId=null;this.La=this.Tb=this.B=this.isInitialized=!1;this.cards=[];this.Mb=this.V=this.Ja=this.D=this.Ta=this.j=null;this.ea=[];this.xa=this.J=this.Zf=this.Ea=null;this.I=0;this.Aa=new g.Jp(function(){},c.Z.dh?4E3:3E3);
g.D(this,this.Aa);this.kb=new g.Jp(function(){});
g.D(this,this.kb);this.va=new Rdb(c,function(e,f,h,l,m,n){R4(d,e,f,h,l,m,n)});
this.Y=new g.T({G:"div",N:"iv-drawer",X:{id:"iv-drawer"},W:[{G:"div",N:"iv-drawer-header",X:{"aria-role":"heading"},W:[{G:"span",N:"iv-drawer-header-text"},{G:"button",Ia:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"\u0421\u043a\u0440\u044b\u0442\u044c \u043f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0438",tabindex:"0"}}]},{G:"div",N:"iv-drawer-content"}]});g.D(this,this.Y);this.C=this.Y.element;this.ib=new g.OQ(this.Y,330);g.D(this,this.ib);this.Wb=g.$e("iv-drawer-header-text",this.C);
this.u=g.$e("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Tb&&T4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Tb=d.B)&&U4(d)});
this.Sa=new g.cI(this);g.D(this,this.Sa);this.F.addEventListener("videodatachange",this.Fs.bind(this))},$db=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){T4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){U4(a)});
var c=b.headerText;g.Af(a.Wb,c);a.V&&a.V.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ea=g.BE(b.trackingParams);a.J=g.BE(b.closeTrackingParams);a.Zf=g.BE(b.iconTrackingParams)},aeb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.F.T().experiments.ob("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.gE(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Qi:{},Ao:null,Zk:e.trackingParams?g.BE(e.trackingParams):null,Zf:f&&f.trackingParams?g.BE(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
gB:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};V4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.gE(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:W4(a,c,b,f),sponsored:!1,Qi:S4(f,e,f.command),Ao:f.trackingParams?g.BE(f.trackingParams):null,Zk:e.trackingParams?g.BE(e.trackingParams):null,Zf:l&&l.trackingParams?g.BE(l.trackingParams):null,imageUrl:X4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.gE(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,gB:null,title:f.title?g.gE(f.title):"",customMessage:f.callToAction?g.gE(f.callToAction):"",url:g.K(f.command,g.pM).url?M4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.K(f.command,g.pM).url}):null,onClickCommand:null};V4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.gE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:W4(a,c,b,e),sponsored:!1,Qi:S4(e,f,e.endpoint),Ao:e.trackingParams?g.BE(e.trackingParams):null,Zk:f.trackingParams?g.BE(f.trackingParams):null,Zf:l&&l.trackingParams?g.BE(l.trackingParams):null,channelId:g.K(e.endpoint,Y4).browseId,customMessage:e.customText?g.gE(e.customText):null,YW:X4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.gE(e.channelName):"",metaInfo:[e.subscriberCountText?g.gE(e.subscriberCountText):""],url:M4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.K(e.endpoint,Y4).canonicalBaseUrl?g.K(e.endpoint,Y4).canonicalBaseUrl:"/channel/"+g.K(e.endpoint,Y4).browseId}),onClickCommand:null};V4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.gE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:W4(a,c,b,e),sponsored:!1,Qi:S4(e,f,e.action),Ao:e.trackingParams?g.BE(e.trackingParams):null,Zk:f.trackingParams?g.BE(f.trackingParams):null,Zf:l&&l.trackingParams?g.BE(l.trackingParams):null,fE:X4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.gE(e.customMessage):null,playlistVideoCount:g.gE(e.playlistVideoCount),title:e.playlistTitle?g.gE(e.playlistTitle):"",metaInfo:[e.channelName?g.gE(e.channelName):
"",e.videoCountText?g.gE(e.videoCountText):""],url:M4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Ydb(e.action)}),onClickCommand:null};V4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.gE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:W4(a,c,b,e),sponsored:!1,Qi:S4(e,f,e.action),Ao:e.trackingParams?g.BE(e.trackingParams):null,Zk:f.trackingParams?g.BE(f.trackingParams):null,Zf:l&&l.trackingParams?g.BE(l.trackingParams):null,fE:X4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.gE(e.lengthString):null,customMessage:e.customMessage?g.gE(e.customMessage):null,title:e.videoTitle?g.gE(e.videoTitle):"",metaInfo:[e.channelName?g.gE(e.channelName):
"",e.viewCountText?g.gE(e.viewCountText):""],isLiveNow:!!e.badge,url:M4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Ydb(e.action)}),onClickCommand:null};V4(a,b)}}}}}a.I++},X4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},W4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},ceb=function(a,b){if(b=beb(a,b))b===a.j&&(a.j=null),a.F.removeCueRange(b.og.id),g.xf(b.JK),g.wb(a.cards,b),a.aF(),Z4(a)},T4=function(a,b,c){if(!a.B){a.ib.show();
a.Ta=new g.Jp(function(){g.Rp(a.context.F.getRootNode(),g.WW.IV_DRAWER_OPEN)},0);
a.Ta.start();a.Sa.S(a.u,"mousewheel",function(h){a.Aa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.FE();d&&a.Ea&&a.J&&g.iP(d,[a.Ea,a.J]);b={TRIGGER_TYPE:b};for(var e=g.t(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.sV||(f.sV=!0,deb(a.context.logger,f.og.Qi.GU,b)),d&&g.iP(d,[f.og.Ao]);v4(a.F);c&&(a.D=new g.Jp(function(){a.Ja=a.V;a.Mb.focus()},330),a.D.start())}},U4=function(a){a.B&&(a.ib.hide(),g.Pz(a.Sa),g.Tp(a.context.F.getRootNode(),g.WW.IV_DRAWER_OPEN),a.B=!1,v4(a.F),a.D&&a.D.stop(),a.D=new g.Jp(function(){a.Ja&&(a.Ja.focus(),a.Ja=null)},330),a.D.start())},feb=function(a){g.Sp(a.ub(),
[g.WW.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.KS(a.F,a.C,5);eeb(a);a.V=g.$e("ytp-cards-button",a.F.getRootNode());a.Mb=g.$e("iv-drawer-close-button",a.C);a.isInitialized=!0},eeb=function(a){var b=g.$e("iv-drawer-close-button",a.C);
a.context.j.Qa(b,"click",a.N2,a);a.context.j.Qa(a.u,"touchend",function(){a.Aa.start()});
a.context.j.Qa(a.u,"scroll",a.f3,a);a.context.u.subscribe("onHideControls",function(){a.La=!0});
a.context.u.subscribe("onShowControls",function(){a.La=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.La=g.Qp(a.F.getRootNode(),"ytp-autohide")});
a.ea.push(g.pC("iv-button-shown",a.S4,a));a.ea.push(g.pC("iv-button-hidden",a.R4,a));a.ea.push(g.pC("iv-teaser-shown",a.NZ,a));a.ea.push(g.pC("iv-teaser-hidden",a.T4,a));a.ea.push(g.pC("iv-teaser-clicked",a.MZ,a))},geb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.K(b.onClickCommand,g.X$a))?void 0:c.targetId)?(a.xa=b,!0):!1},heb=function(a,b){a.xa=b;
var c=a.F.getVideoData();if(!c)return!1;c=a.F.K("embeds_web_enable_video_data_refactoring_offline_and_progress_bar")?g.IL(c):c.multiMarkersPlayerBarRenderer;if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.K(h[0],g.aPa))?void 0:d.timeRangeStartMillis)||0,a.xa=null,!0}return!1},
V4=function(a,b){if(!geb(a,b)||heb(a,b)){var c=ieb(a,b);
if(c){var d={og:b,JK:c.element,sV:!1};if(!b.onClickCommand){a.isInitialized||feb(a);ceb(a,b.id);var e=jeb(a,d);g.Fb(a.cards,e,0,d);c.Fa(a.u,e);a.aF()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,Z4(a),keb(a,d),T4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.F.getCurrentTime(),5E3>c&&c>b.startMs&&leb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){leb(a,d)}),Z4(a))}}},ieb=function(a,b){switch(b.type){case "simple":a=a.va;
var c=b.displayDomain?{G:"div",N:"iv-card-image-text",qa:b.displayDomain}:void 0;var d=Udb(b);c={G:"div",Ia:["iv-card"],W:[{G:"a",N:"iv-click-target",X:{href:b.url?L4(b.url)||"":""},W:[O4(b.imageUrl,c),{G:"div",N:"iv-card-content",W:[N4("h2",void 0,b.title),d]}]}]};c=new g.T(c);P4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.va;c={G:"div",Ia:["iv-card","iv-card-channel"],W:[{G:"a",Ia:["iv-click-target"],X:{href:L4(b.url)||"","data-ytid":b.channelId},W:[O4(b.YW),{G:"div",
N:"iv-card-content",W:[Sdb(b),{G:"h2",N:"iv-card-primary-link",qa:b.title},Tdb(b)]}]}]};c=new g.T(c);P4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.va;c={G:"div",Ia:["iv-card","iv-card-playlist"],W:[{G:"a",N:"iv-click-target",X:{href:L4(b.url)||""},W:[O4(b.fE,{G:"div",N:"iv-card-image-overlay",W:[{G:"span",N:"iv-card-playlist-video-count",qa:b.playlistVideoCount}]}),{G:"div",N:"iv-card-content",W:[Sdb(b),N4("h2","iv-card-primary-link",b.title),Tdb(b)]}]}]};c=new g.T(c);
P4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.va;var e=!g.sb(b.offers);c=["iv-card"];d="";var f=Udb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",N:"iv-card-offer-price",qa:f.price}),f.merchant&&e.push({G:"div",N:"iv-card-offer-merchant",qa:f.merchant}),f={G:"div",W:e});e=b.url?L4(b.url)||"":"";c={G:"div",Ia:c,X:{tabindex:"0"},W:[{G:"a",Ia:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",N:"iv-card-content",W:[b.sponsored?{G:"div",N:"iv-card-sponsored",W:["\u0420\u0435\u043a\u043b\u0430\u043c\u0430",{G:"div",N:"iv-ad-info-container",W:[{G:"div",N:"iv-ad-info",qa:"{{adInfo}}"},{G:"div",N:"iv-ad-info-icon-container",W:[{G:"div",N:"iv-ad-info-icon"},{G:"div",N:"iv-ad-info-callout"}]}]}]}:"",{G:"a",N:"iv-click-target",X:{href:e},W:[N4("h2",d,b.title),f]}]}]};c=new g.T(c);d=g.qf("span");g.Af(d,"\u042d\u0442\u043e \u043a\u043e\u043d\u0442\u0435\u043a\u0441\u0442\u043d\u0430\u044f \u0440\u0435\u043a\u043b\u0430\u043c\u0430. \u0415\u0435 \u043f\u043e\u043a\u0430\u0437 \u043c\u043e\u0436\u0435\u0442 \u043e\u043f\u043b\u0430\u0447\u0438\u0432\u0430\u0442\u044c\u0441\u044f \u043f\u0440\u043e\u0434\u0430\u0432\u0446\u043e\u043c.");
c.je(d,"adInfo");P4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.va;d=b.videoDuration?{G:"span",N:"iv-card-video-duration",qa:b.videoDuration}:void 0;f=b.isLiveNow?{G:"span",Ia:["yt-badge","yt-badge-live"],qa:"\u0421\u0415\u0419\u0427\u0410\u0421 \u0412 \u041f\u0420\u042f\u041c\u041e\u041c \u042d\u0424\u0418\u0420\u0415"}:null;e={G:"div",Ia:["iv-card","iv-card-video"],W:[{G:"a",N:"iv-click-target",X:{href:(null==(c=b.url)?void 0:L4(c))||""},W:[O4(b.fE,d),{G:"div",N:"iv-card-content",
W:[Sdb(b),N4("h2","iv-card-primary-link",b.title),Tdb(b),f]}]}]};c=new g.T(e);P4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;default:return null}return b},jeb=function(a,b){if(0===a.cards.length)return 0;
a=g.ob(a.cards,function(c){return b.og.startMs>c.og.startMs||b.og.startMs===c.og.startMs&&b.og.timestamp>=c.og.timestamp?!0:!1});
return-1===a?0:a+1},meb=function(a){return a.j?"productListing"===a.j.og.type:g.bm(a.cards,function(b){return"productListing"===b.og.type})},Z4=function(a){g.Vp(a.F.getRootNode(),"ytp-cards-shopping-active",meb(a))},leb=function(a,b){if(!g.Qp(a.F.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.FE(),d=a.j?a.j.og.Zf:a.Zf;
c&&d&&g.jP(c,[d]);a.j=b;Z4(a)}(c=a.isInitialized&&"none"==a.ub().style.display)||(c=a.context.F.getPlayerState(),d=0===c&&0===a.context.F.getCurrentTime(),c=!(1===c||3===c||d));c||b.og.teaserDurationMs&&a.F.Oz(!0,{teaserText:b.og.teaserText,durationMs:b.og.teaserDurationMs,onClickCommand:b.og.onClickCommand});a.kb.isActive()||((!a.B||!a.Aa.isActive()&&a.La)&&keb(a,b),a.kb.start(910+b.og.teaserDurationMs))}},keb=function(a,b){a.Y.yb?(b=new A4([0,
a.u.scrollTop],[0,b.JK.offsetTop],600,ldb),a.context.B.Qa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Qa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.$P(a.Y,!0),a.u.scrollTop=b.JK.offsetTop,g.$P(a.Y,!1))},$4=function(a){return a.j&&a.j.og?a.j.og:a.cards[0]&&a.cards[0].og?a.cards[0].og:null},beb=function(a,b){return g.nb(a.cards,function(c){return c.og.id===b})},a5=function(a,b,c){Q4.call(this,a,b);
this.annotation=c;this.isActive=!1},neb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},b5=function(a,b,c){a5.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},oeb=function(a,b){var c=void 0===c?0:c;
var d=jdb(b).width;g.Rm(b,d);c=new rdb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,kdb);g.D(a,c);a.context.B.Qa(c,"begin",function(){g.Xm(b,!0)});
c.play()},reb=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ia:["iv-branding-context-name"],qa:b.channel_name}),d=a.createElement({G:"div",Ia:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.lU(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.F),a.j.Fa(d));var f=a.createElement({G:"div",Ia:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ia:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Xm(h,!1);var l=a.createElement({G:"div",Ia:["branding-context-container-outer"]});l.appendChild(h);g.Lm(l,"right",b.image_width+"px");g.sf(a.ub(),l);a.B=new g.Jp(function(){peb(a,h,l)},500);
g.D(a,a.B);a.context.j.Qa(a.ub(),"mouseover",function(){qeb(a,h,l,f,b.image_height)});
a.context.j.Qa(a.ub(),"mouseout",function(){a.B.start()})}},qeb=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Wm(b);a.j||(b.style.width=g.Qm(f.width,!0),c.style.width=g.Qm(f.width,!0));g.Lm(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Lm(d,"right","1px");a.C=!0;g.Xm(b,!0);a.D=new g.Jp(function(){g.Rp(this.ub(),"iv-branding-active")},0,a);
a.D.start()}},peb=function(a,b,c){g.Tp(a.ub(),"iv-branding-active");
a.I=new g.Jp(function(){g.Xm(b,!1);a.j||(c.style.width=g.Qm(0,!0))},250);
a.I.start();a.C=!1},seb=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Z=c;this.videoData=d;this.logger=e;this.F=f;this.u=h},teb=function(a,b,c){a5.call(this,a,b,c);
var d=this;this.V=this.isCollapsed=this.Y=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({G:"div",Ia:["iv-promo-contents"]});this.D=new g.Jp(function(){d.j.setAttribute("aria-hidden","true");g.Xm(d.B,!1);g.Xm(d.u,!0)},700,this);
g.D(this,this.D)},veb=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.ub().setAttribute("aria-hidden","true");a.ub().setAttribute("aria-label","\u041f\u0440\u043e\u0434\u0432\u0438\u0436\u0435\u043d\u0438\u0435");a.ub().tabIndex=0;var e=a.annotation.Ye(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ia:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",X:{src:f,"aria-hidden":"true"}});
h.appendChild(f);b.video_duration&&!b.is_live?(f=a.createElement({G:"span",N:"iv-promo-video-duration",qa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",N:"iv-promo-playlist-length",qa:b.playlist_length.toString()}),h.appendChild(f));e&&R4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",N:"iv-promo-txt"}),g.xe(f,L4(e)),a.j=f):a.j=a.createElement({G:"div",N:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",
W:[{G:"strong",qa:b.text_line_1}]});var m=a.createElement({G:"p",W:[{G:"span",N:"iv-promo-link",qa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ia:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ia:["iv-button","iv-promo-button"],W:[{G:"span",N:"iv-button-content",qa:f}]});var p=a.createElement({G:"div",N:"iv-promo-button-container"});p.appendChild(f);e&&R4(a,a.ub(),e,a.annotation.id,b.session_data,
void 0,c)}g.Rp(a.j,"iv-click-target");e&&R4(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",W:[{G:"span",qa:b.text_line_1}]}),m=a.createElement({G:"p",W:[{G:"strong",qa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ia:["yt-badge","iv-promo-badge-live"],qa:"\u0421\u0415\u0419\u0427\u0410\u0421 \u0412 \u041f\u0420\u042f\u041c\u041e\u041c \u042d\u0424\u0418\u0420\u0415"})),g.Rp(a.j,"iv-click-target"),e&&R4(a,a.j,e,a.annotation.id,
b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&a.J.appendChild(p);c=a.createElement({G:"div",N:"iv-promo-actions"});a.u=a.createElement({G:"button",Ia:["iv-promo-expand","ytp-button"]});a.u.title="\u0420\u0430\u0437\u0432\u0435\u0440\u043d\u0443\u0442\u044c";a.context.j.Qa(a.u,"click",function(q){ueb(a,5E3,q)});
c.appendChild(a.u);g.Xm(a.u,!1);a.context.j.Qa(a.ub(),"mouseover",a.Z3,a);a.context.j.Qa(a.ub(),"mouseout",a.Y3,a);a.context.j.Qa(a.ub(),"touchend",function(q){ueb(a,5E3,q)});
a.B=a.createElement({G:"button",Ia:["iv-promo-close","ytp-button"]});a.B.title="\u0417\u0430\u043a\u0440\u044b\u0442\u044c";a.context.j.Qa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.U3:a.T3,a);c.appendChild(a.B);g.Sp(a.ub(),d);h&&(g.sf(a.ub(),h),n&&h.appendChild(n));g.sf(a.ub(),a.J);g.sf(a.ub(),c)},ueb=function(a,b,c){c.stopPropagation();
web(a);xeb(a,b);a.j.focus()},yeb=function(a){a.isCollapsed||a.V||a.C||(g.Rp(a.ub(),"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},web=function(a){a.D.stop();
a.isCollapsed&&(g.Up(a.ub(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Xm(a.u,!1),g.Xm(a.B,!0))},xeb=function(a,b){a.C||(a.C=g.ag(function(){zeb(this);
yeb(this)},b,a))},zeb=function(a){a.C&&(g.Ea.clearTimeout(a.C),a.C=null)},Aeb=function(a){this.F=a},deb=function(a,b,c){b&&(c?c5(a,b.map(function(d){return g.yp(d,c)})):c5(a,b))},c5=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.t(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.ZB(m,f);d&&(e++,0!==d&&a.F.sendVideoStatsEngageEvent(d,f))},Beb=function(a){g.AT.call(this,a);
var b=this;this.ea=this.J=!1;this.loadNumber=0;this.I={};this.logger=new Aeb(this.player);this.C=new g.cI(this);this.D=this.zw=null;this.events=new g.cI(this);this.V=this.j=null;this.Y=[];g.D(this,this.C);this.C.S(this.player,"onVideoAreaChange",function(){b.ma("onVideoAreaChange")});
this.C.S(this.player,"onHideControls",function(){b.ma("onHideControls")});
this.C.S(this.player,"onShowControls",function(){b.ma("onShowControls")});
this.C.S(this.player,"resize",function(d){b.ma("resize",d)});
this.C.S(this.player,"presentingplayerstatechange",function(d){b.ma("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.OZ,this);this.subscribe("resize",this.cH,this);this.player.T().Aa.subscribe("vast_info_card_add",this.GW,this);g.D(this,this.events);this.xa=this.createElement({G:"div",N:"video-custom-annotations"});this.u=new g.T({G:"div",Ia:["ytp-player-content","ytp-iv-player-content"]});g.D(this,this.u);g.KS(this.player,this.u.element,4);this.u.hide();this.B=new g.T({G:"div",Ia:["ytp-iv-video-content"]});g.D(this,this.B);a=this.createElement({G:"div",N:"video-annotations"});
a.appendChild(this.xa);this.B.element.appendChild(a);this.lw()&&this.load();var c=this.createElement({G:"style"});(g.Xe("HEAD")[0]||document.body).appendChild(c);g.ab(this,function(){g.xf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Ceb=function(a){a=a.createElement({G:"div",
Ia:["annotation","annotation-type-custom"]});g.Xm(a,!1);return a},Deb=function(a,b){b=!b.isCued()&&!g.S(b,1024);
g.$P(a.u,b);g.$P(a.B,b)},Eeb=function(a,b,c){a.J=!0;
a.D=g.Ly(b,c)},Feb=function(a,b){for(var c={},d=g.t(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ja(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Feb(a,e))}return c},Jeb=function(a){var b=a.player.getVideoData();
if(b.Ta){var c=a.player.T().Aa.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Fy(h)&&h.responseXML?h.responseXML:null)&&Geb(a,h)}};
g.nA()&&(d.onFinish=Heb(a,d.onFinish));d.postParams={ic_only:"1"};Ieb(d,c);a.J=!0;g.Ly(b.Ta,d)}}},Ieb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.iB&&(a.postParams.ic_coll=b.iB);b.KK&&(a.postParams.ic_xml=b.KK);b.qI&&(a.postParams.ic_track=b.qI)},Keb=function(a){var b=new g.T({G:"div"});
g.Xm(b.element,!1);var c=new Zdb(a.player,b.element,d5(a));g.D(c,b);b.Fa(a.u.element);c.VD();return c},d5=function(a){if(!a.V){var b=new sdb(a);
g.D(a,b);var c=new g.Uk(a);g.D(a,c);a.V=new seb(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.Mh)}return a.V},Geb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.FE();if(e){var f=g.EE();f&&g.qy(g.aP)(void 0,e,f,[g.BE(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Feb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=K4(f.type,Leb),p=K4(f.style,Meb),q=Idb(f.data),r=0!==q.length?JSON.parse(q):{};var u=f.action;f=Odb;if(null==u)var x=null;else if(g.Ia(u)){l=[];for(var z=g.t(u),B=z.next();!B.done;B=z.next()){var F=f(B.value);
F&&l.push(F)}x=l}else{var G=f(u);x=G?[G]:[]}e=m&&n?new Pdb(m,n,p,x,r):null}else e=null}catch(W){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var E=Ceb(f),L=null;switch(l.type){case "branding":if(f.player.T().wd)break;f.u.element.appendChild(E);L=new b5(E,d5(f),l);break;case "promotion":g.KS(f.player,E,4),L=new teb(E,d5(f),l)}L&&L.VD();if(f=L)g.D(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Keb(a),g.D(a,a.j));if("card"===e.type){c=a.j;var P=e&&e.data&&e.data.card_type;
f=e.data;if(P)switch(l=f.tracking||{},l={GU:l.impression,click:l.click,close:l.close,cY:l.teaser_impression,nI:l.teaser_click},E=f.tracking_params||{},L=null,P){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Qi:l,Ao:E.card?g.BE(E.card):null,Zk:E.teaser?g.BE(E.teaser):null,Zf:E.icon?g.BE(E.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,YW:f.image_url,title:f.title,metaInfo:f.meta_info,url:M4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};V4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Qi:l,Ao:E.card?g.BE(E.card):null,Zk:E.teaser?
g.BE(E.teaser):null,Zf:E.icon?g.BE(E.icon):null,fE:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:M4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};V4(c,e);break;case "productListing":f.signin_url&&(L=M4({target:"current",value:f.signin_url}));P=[];for(var U=f.offers||[],aa=0;aa<U.length;aa++)P.push(new Vdb(g.Ne(U[aa].merchant),g.Ne(U[aa].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Qi:l,Ao:E.card?g.BE(E.card):null,Zk:E.teaser?g.BE(E.teaser):null,Zf:E.icon?g.BE(E.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,gB:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:M4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),q8a:L,p8a:f.signin_title?f.signin_title:void 0,o8a:f.signin_message?f.signin_message:void 0,offers:P,onClickCommand:null};V4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Qi:l,Ao:E.card?g.BE(E.card):
null,Zk:E.teaser?g.BE(E.teaser):null,Zf:E.icon?g.BE(E.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,gB:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:M4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};V4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Qi:l,Ao:E.card?g.BE(E.card):null,Zk:E.teaser?g.BE(E.teaser):null,Zf:E.icon?g.BE(E.icon):null,fE:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:M4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},V4(c,e)}}else $db(a.j,e);c=!0}}c&&
(v4(a.player),a.cH())},Neb=function(a,b){var c=!1;
a.j||(a.j=Keb(a),g.D(a,a.j));for(var d=g.t(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(aeb(a.j,e.cardRenderer),c=!0);var f;!c||null!=(f=a.player.getVideoData())&&g.MM(f)||(c=a.j,d=b.headerText?g.gE(b.headerText):"",g.Af(c.Wb,d),c.V&&c.V.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ea=b.trackingParams?g.BE(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.BE(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Zf=b.icon.infoCardIconRenderer.trackingParams?g.BE(b.icon.infoCardIconRenderer.trackingParams):null,v4(a.player),a.cH())},Oeb=function(a,b,c,d,e){if(!a.player.T().wd){var f=[];
b.navigationEndpoint&&g.K(b.navigationEndpoint,Y4)&&g.K(b.navigationEndpoint,Y4).browseId&&f.push(new Ldb("openUrl","click",new Jdb("/channel/"+g.K(b.navigationEndpoint,Y4).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.K(b.subscribeButton,
g.FM)){d.channel_id=g.K(b.subscribeButton,g.FM).channelId;var l;b=g.K(b.subscribeButton,g.FM);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.gE(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.gE(b.subscriberCountText))):(b.subscriberCountText&&(e=g.gE(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.gE(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.K(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.q3))?void 0:m.url)||"";l={subscribeText:g.gE(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.gE(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Pdb(c,"branding","branding",f,d);l=Ceb(a);a.u.element.appendChild(l);f=new b5(l,d5(a),f);f.VD();g.D(f,f);a.I[c]=f}},Heb=function(a,b){return function(){var c=g.ya.apply(0,arguments);
a.isDisposed()||a.Y.push(g.Bp.Bi(function(){b.apply(null,g.v(c))}))}},Peb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.xS.prototype.Oz=g.ca(18,function(a,b){var c=g.NT(this.wb());c&&c.Oz(a,b)});
var x4={},y4=null;g.Ta(A4,g.cq);g.k=A4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.hd())return!1;z4(this);this.startTime=a=g.Ra();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.YG();this.Gl("play");-1==this.j&&this.Gl("resume");this.j=1;var b=g.Na(this);b in x4||(x4[b]=this);ndb();odb(this,a);return!0};
g.k.stop=function(a){z4(this);this.j=0;a&&(this.progress=1);pdb(this,this.progress);this.Gl("stop");this.Hq()};
g.k.pause=function(){this.hd()&&(z4(this),this.j=-1,this.Gl("pause"))};
g.k.oa=function(){0==this.j||this.stop(!1);this.Gl("destroy");A4.Jf.oa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.eJ=function(){this.Gl("animate")};
g.k.Gl=function(a){this.dispatchEvent(new qdb(a,this))};
g.Ta(qdb,g.ib);g.Ta(B4,A4);B4.prototype.B=function(){};
B4.prototype.eJ=function(){this.B();B4.Jf.eJ.call(this)};
B4.prototype.Hq=function(){this.B();B4.Jf.Hq.call(this)};
B4.prototype.YG=function(){this.B();B4.Jf.YG.call(this)};
g.Ta(rdb,B4);rdb.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var Y4=new g.Br("browseEndpoint");g.w(sdb,g.C);g.k=sdb.prototype;g.k.Qa=function(a,b,c,d){c=(0,g.Oa)(c,d||this.u);a=g.Iz(a,b,c);this.j.push(a);return a};
g.k.BG=function(a,b,c,d){c=(0,g.Oa)(c,d||this.u);a=g.Poa(a,b,c);this.j.push(a);return a};
g.k.Fc=function(a){g.Jz(a);g.wb(this.j,a)};
g.k.Hf=function(){g.Jz(this.j);this.j.length=0};
g.k.oa=function(){this.Hf();g.C.prototype.oa.call(this)};g.w(vdb,g.AT);g.k=vdb.prototype;g.k.load=function(){g.AT.prototype.load.call(this);if(!E4(this)){var a=g.aAa(this.player.getVideoData());a?(a=udb(a,wdb(this)),F4(this,a,!1)):xdb(this)}};
g.k.unload=function(){F4(this,null);this.B&&(this.B.abort(),this.B=null);g.AT.prototype.unload.call(this)};
g.k.rh=function(a,b){return E4(this)?"loadCustomEndscreenRenderer"===a?(a=udb(b,"new"),F4(this,a),!0):null:null};
g.k.getOptions=function(){return E4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Cb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Qeb.length;f++){var h=Math.abs(b.width-Qeb[f]);if(-1===e||d>=h)e=f,d=h}d=Reb[e];this.u&&g.Lm(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Vm(e.element,m,f);g.Rm(e.element,n,p);g.Up(e.element,Seb);256<m||256<f?g.Rp(e.element,"ytp-ce-large-round"):96<m||96<f?g.Rp(e.element,"ytp-ce-medium-round"):g.Rp(e.element,"ytp-ce-small-round");g.Up(e.element,Teb);m=h.left+h.width/2;h=h.top+l/2;g.Rp(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Up(e.element,Reb);g.Rp(e.element,d);(e=g.Ye(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Lm(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())J4(this,this.endscreen.impressionUrls),(a=g.FE())&&this.endscreen.visualElement&&g.hP(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.Rp(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Rp(b,"ytp-ce-shown");J4(this,c.impressionUrls);(b=g.FE())&&g.hP(b,c.visualElement);this.player.T().I&&this.player.Na("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Tp(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Tp(b,"ytp-ce-shown");this.player.T().I&&this.player.Na("endscreenelementhidden",a)}};
g.k.q8=function(a){var b=this;a.target===window&&(new g.Jp(function(){for(var c=g.t(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Up(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Qeb=[346,426,470,506,570,640,853,1280,1920],Reb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Teb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Seb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Kdb={Yma:"current",lKa:"new"};var Mdb={CLOSE:"close",JNa:"openUrl",SUBSCRIBE:"subscribe"},Ndb={Dla:"click",CLOSE:"close",Cwa:"hidden",oSa:"rollOut",pSa:"rollOver",KTa:"shown"};Pdb.prototype.Ye=function(){var a=Qdb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Meb={oha:"anchored",iZ:"branding",CHANNEL:"channel",Oma:"cta",Fwa:"highlightText",AAa:"label",PLAYLIST:"playlist",aQa:"popup",pWa:"speech",SUBSCRIBE:"subscribe",jZa:"title",VIDEO:"video",X3a:"website"},Leb={iZ:"branding",Cja:"card",Voa:"drawer",Ewa:"highlight",rGa:"marker",lRa:"promotion",TEXT:"text",w5a:"widget"};g.w(Q4,g.C);g.k=Q4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.XD(a,b,{id:c,namespace:"annotations_module"});d&&this.Za.set(a,d);e&&this.gb.set(a,e);this.context.F.ye([a])};
g.k.VD=function(){this.context.u.subscribe("resize",this.aF,this)};
g.k.ub=function(){return this.element};
g.k.fJ=function(a,b,c,d,e,f){if(this.tb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.xf(this.ub())};
g.k.aF=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=L4(a);if(f){var h=Xdb(f,a.target),l=function(){a.j&&e.context.F.pauseVideo();var m=e.context.videoData.D||!1,n=g.wy(f||"");m&&n&&(n.v||n.list)?e.context.F.Ln(n.v,b,n.list,!1):g.IN(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);c5(this.context.logger,c,l,d);Wdb(f)||(c=g.FE(),d=b.itct,c&&d&&g.kP(c,g.BE(d)))}};
g.k.oa=function(){this.Za.clear();this.gb.clear();g.C.prototype.oa.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.D(this,a);return a.element};g.w(Zdb,Q4);g.k=Zdb.prototype;g.k.Fs=function(){this.xa&&V4(this,this.xa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.F.getRootNode())?(a=g.Wm(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.aF=function(){var a=this.isAvailable();g.Xm(this.ub(),a);g.Vp(this.context.F.getRootNode(),g.WW.IV_DRAWER_ENABLED,a);v4(this.F)};
g.k.destroy=function(){this.F.Oz(!1);try{this.F.getRootNode().removeChild(this.C)}catch(a){}g.qC(this.ea);g.Pz(this.Sa);this.Ta&&this.Ta.dispose();this.D&&this.D.dispose();Q4.prototype.destroy.call(this)};
g.k.N2=function(){if(this.B){c5(this.context.logger,$4(this).Qi.close);var a=g.FE();a&&this.J&&g.kP(a,this.J);U4(this)}};
g.k.f3=function(){g.Vp(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.S4=function(){var a=g.FE(),b=$4(this);b=b?b.Zf:this.Zf;a&&b&&g.iP(a,[b])};
g.k.R4=function(){var a=g.FE(),b=$4(this);b=b?b.Zf:this.Zf;a&&b&&g.jP(a,[b])};
g.k.NZ=function(){var a=$4(this);c5(this.context.logger,a.Qi.cY);var b=g.FE();b&&a&&g.iP(b,[a.Zk,a.Zf])};
g.k.T4=function(){var a=g.FE(),b=$4(this);a&&b&&g.jP(a,[b.Zk])};
g.k.MZ=function(a){var b=$4(this),c=g.FE();this.j?a?(a=this.context.logger,c5(a,b.Qi.nI),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Zk&&g.kP(c,b.Zk)):(a=this.context.logger,c5(a,b.Qi.nI),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Zf&&g.kP(c,b.Zf)):(a=this.context.logger,c5(a,b.Qi.nI),a.F.sendVideoStatsEngageEvent(4,void 0),c&&this.Zf&&g.kP(c,this.Zf))};g.w(a5,Q4);a5.prototype.VD=function(){Q4.prototype.VD.call(this);neb(this)};
a5.prototype.show=function(){Q4.prototype.show.call(this);var a=g.FE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.iP(a,[g.BE(b.itct)])};
a5.prototype.hide=function(){Q4.prototype.hide.call(this);var a=g.FE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.jP(a,[g.BE(b.itct)])};g.w(b5,a5);
b5.prototype.show=function(){if(!this.isActive){a5.prototype.show.call(this);if(!this.J){g.Rp(this.ub(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ia:["branding-img","iv-click-target"],X:{"aria-label":"\u041b\u043e\u0433\u043e\u0442\u0438\u043f \u043a\u0430\u043d\u0430\u043b\u0430",src:a.image_url,width:a.image_width,height:a.image_height}});g.Xm(this.u,!1);var b=this.createElement({G:"button",Ia:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.ub().appendChild(b);
var c=this.annotation.Ye();c&&R4(this,b,c,this.annotation.id,a.session_data);reb(this,a);this.J=!0}g.Xm(this.ub(),!0);this.isActive=!0;this.u&&(oeb(this,this.u),g.Rp(this.context.F.getRootNode(),"ytp-branding-shown"))}};
b5.prototype.hide=function(){this.isActive&&(a5.prototype.hide.call(this),g.Xm(this.ub(),!1),this.isActive=!1,g.Tp(this.context.F.getRootNode(),"ytp-branding-shown"))};
b5.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);a5.prototype.destroy.call(this)};g.w(teb,a5);g.k=teb.prototype;g.k.show=function(){this.isActive||(a5.prototype.show.call(this),this.Y||(veb(this),this.Y=!0),g.Xm(this.ub(),!0),g.ag(function(){g.Tp(this.ub(),"iv-promo-inactive")},100,this),this.ub().removeAttribute("aria-hidden"),this.isActive=!0,zeb(this),web(this),xeb(this,this.I))};
g.k.hide=function(){this.isActive&&(g.Rp(this.ub(),"iv-promo-inactive"),this.isActive=!1,this.ub().setAttribute("aria-hidden","true"))};
g.k.fJ=function(a,b,c,d,e,f){return this.isCollapsed?!1:a5.prototype.fJ.call(this,a,b,c,d,e,f)};
g.k.Z3=function(a){this.V=!0;ueb(this,500,a)};
g.k.Y3=function(){this.V=!1;yeb(this)};
g.k.T3=function(a){a.stopPropagation();this.hide()};
g.k.U3=function(a){a.stopPropagation();zeb(this);this.isCollapsed=!0;g.Rp(this.ub(),"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();a5.prototype.destroy.call(this)};g.w(Beb,g.AT);g.k=Beb.prototype;g.k.rh=function(a,b){if(!Peb(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.B8a(b))&&Geb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(ceb(this.j,b),v4(this.player)),!0}return null};
g.k.getOptions=function(){return Peb(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.lw=function(){var a=this.player.T(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.D&&a.ea||g.rS(this.player.app)?!1:1===c&&!b.QR||a.Aa.get(b.videoId)||g.NM(b)||g.OM(b)?!0:!1};
g.k.cH=function(){if(this.B){var a=this.player.jb().getVideoContentRect(!0);g.Vm(this.B.element,a.width,a.height);g.Rm(this.B.element,a.left,a.top)}if(this.j){var b=this.player.yk();a=this.j;b=b.width;g.Vp(a.C,"iv-drawer-small",426>=b);g.Vp(a.C,"iv-drawer-big",1280<=b)}};
g.k.OZ=function(a){Deb(this,a.state);g.S(a.state,2)&&(this.lk()&&this.zo()&&2!==this.player.getPresentingPlayerType()&&this.Pz(!1),this.Oz(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Fy(h)&&h.responseXML?h.responseXML:null)&&(Geb(b,h),g.Rp(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.AT.prototype.load.call(this);Deb(this,this.player.Db());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.nA()&&(a=Heb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().Aa.get(d);f&&Ieb(e,f);f=f&&(f.KK||f.iB);if(!c.Kw||f)c.Ta?Eeb(this,c.Ta,e):(this.zw=function(){if(!b.J)b.onVideoDataChange(e);var h=b.player.getVideoData();if((null==h?0:g.MM(h))&&!b.ea){var l,m;if(h=null==(l=h.fd)?void 0:null==(m=l.cards)?void 0:m.cardCollectionRenderer)Neb(b,h),b.ea=!0}},this.player.addEventListener("videodatachange",this.zw));
g.KS(this.player,this.B.element,4);this.cH();(f=g.NM(c))&&Neb(this,f);(f=g.OM(c))&&f.featuredChannel&&Oeb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ta&&Eeb(this,b.Ta,a)};
g.k.unload=function(){this.player.If("annotations_module");for(var a=g.t(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.V=null;this.j&&(this.j.destroy(),this.j=null,v4(this.player));this.J=!1;this.D&&(this.D.abort(),this.D=null);this.ea=!1;this.I={};this.u.hide();g.AT.prototype.unload.call(this);this.B.detach();this.zw&&(this.player.removeEventListener("videodatachange",this.zw),this.zw=null)};
g.k.GW=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Jeb(this):this.load())};
g.k.lk=function(){return!!this.j&&this.j.isAvailable()};
g.k.zo=function(){return!!this.j&&this.j.B};
g.k.Pz=function(a,b,c){b=void 0===b?!1:b;this.lk();this.j&&(a?c?T4(this.j,c,b):T4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):U4(this.j))};
g.k.Oz=function(a,b){this.player.ma(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.oa=function(){this.player.T().Aa.unsubscribe("vast_info_card_add",this.GW,this);g.Tp(this.player.getRootNode(),g.WW.IV_DRAWER_OPEN);for(var a=this.Y,b=g.Bp,c=0,d=a.length;c<d;c++)b.Bm(a[c]);this.Y.length=0;g.AT.prototype.oa.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.D(this,a);return a.element};g.zT("annotations_module",Beb);g.zT("creatorendscreen",vdb);})(_yt_player);
