(function(g){var window=this;'use strict';var Ueb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Veb=function(a){return g.DK(a)?g.gJ(a.experiments,"web_player_caption_language_preference_stickiness_duration"):0},Web=function(a,b){var c=new g.YK;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.u=a.u;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},Xeb=function(a,b){var c,d,e;
return g.A(function(f){if(1==f.j)return c=a+"|"+b,g.y(f,g.uB(),2);if(3!=f.j){d=f.u;if(!d)throw g.HA("gct");return g.y(f,g.OL(d),3)}e=f.u;return f.return(e.get("captions",c))})},Yeb=function(a,b,c){Xeb(a,b).then(function(d){d&&c(d.trackData,new g.YK(d.metadata))})},afb=function(a){if(!Zeb.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace($eb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},bfb=function(){return g.Uz("yt-player-caption-display-settings")},e5=function(){this.segments=[]},cfb=function(a,b){var c=g.Jb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.tb(a.segments,c),g.tb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.Fb(a.segments,c,0,b),g.Fb(a.segments,c+1,0,b)))},dfb=function(a,b,c,d,e,f){g.C.call(this);
this.policy=a;this.player=b;this.Y=c;this.onLoadCallback=d;this.D=e;this.V=f;this.C=new e5;this.I=-1;this.B=this.u=this.j=null;this.J=new g.Jp(this.mV,1E3,this);this.events=new g.cI(this);g.D(this,this.J);g.D(this,this.events);this.events.S(b,"SEEK_COMPLETE",this.sz);this.sz();this.mV()},efb=function(a){return a.j&&a.j.C?a.j.C+a.player.Jd()<a.player.getCurrentTime():!1},ffb=function(a,b){var c=g.iH(b,a.policy,{}).Ye(),d={format:"RAW",
withCredentials:!0};if(a.policy.Aa){d.method="POST";var e=b.Cs(),f=(0,g.PX)([120,0]);e&&g.yL(e,g.WLa);d.postBody=f}a.D&&(d.responseType="arraybuffer");a.B=g.Py(c,d,3,100).then(function(h){a:{h=h.xhr;a.isDisposed();if(a.u){var l=!(a.D?h.response:h.responseText)||400<=h.status,m=g.Ova(h);if(m){h=g.iH(a.u,a.policy,{});a.u.Bk(h,m);ffb(a,a.u);break a}if(l)a.player.ya("capfail",{status:h.status});else if(a.player.Rh().ri("fcb_r"),m=a.u.fb[0].Ma,null!=a.onLoadCallback&&a.I!==m){l=a.u.fb[0];if(a.D)a.onLoadCallback(h.response,
1E3*(l.startTime+a.player.Jd()));else a.onLoadCallback(h.responseText,1E3*(l.startTime+a.player.Jd()));a.I=m}}a.u=null;a.B=null}}).Xj(function(h){a.u=null;
a.B=null;var l;a.player.ya("capfail",{status:null==(l=h.xhr)?void 0:l.status})});
a.u=b;cfb(a.C,a.u.fb[0].Ma)},f5=function(a,b){g.DT.call(this,b.T());
this.u=a;this.F=b;this.B=null;this.D=!1;this.I=g.FK(this.F.T())&&!this.u.isManifestless},hfb=function(a,b){var c=[],d;
for(d in a.u.j)if(a.u.j.hasOwnProperty(d)){var e=a.u.j[d];if(g.XLa(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.F.T().K("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.Vcb.get(e);null==q&&(q=gfb[e]||gfb[e.replace(/-/g,"_")],g.Vcb.set(e,q));h=q||h}c.push(new g.YK({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
ifb=function(a,b){return null!=b&&b in a.u.j?a.u.j[b]:null},jfb=function(a,b,c){var d=[],e;
for(e in a.u.j)if(a.u.j.hasOwnProperty(e)){var f=a.u.j[e];if(g.XLa(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},lfb=function(){var a=void 0;
a=void 0===a?{}:a;var b="suggest_correction"in kfb?kfb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c.yA=d;var e=function(f){return function(){return String(a[f.yA])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.yA+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.yA,"gi"),e);c={yA:c.yA}}return b},g5=function(a,b,c,d,e,f,h,l,m,n){var p={};
Object.assign(p,b);Object.assign(p,a.params);Object.assign(p,c);var q={};Object.assign(q,b.Be);a.params.Be&&Object.assign(q,a.params.Be);Object.assign(q,c.Be);p.Be=q;var r=1===p.oi,u=[{G:"span",N:"captions-text",X:{style:"word-wrap: normal; display: block;"}}],x,z,B;(l=l.ob("caption_edit_on_hover")&&(null==(x=n.getVideoData().getPlayerResponse())?void 0:null==(z=x.captions)?void 0:null==(B=z.playerCaptionsTracklistRenderer)?void 0:B.openTranscriptCommand))&&u.unshift({G:"button",N:"caption-edit",
X:{tabindex:"0","aria-label":lfb()},W:[{G:"svg",X:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},W:[{G:"path",X:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.T.call(this,{G:"div",N:"caption-window",X:{id:"caption-window-"+a.id,dir:r?"rtl":"ltr",tabindex:"0",lang:p.lang},W:u});var F=this;this.I=[];this.Ea=!1;this.u=a;this.La=
this.Ja=null;this.playerWidth=f;this.playerHeight=h;this.J=null;this.maxWidth=.96*f;this.gb=.96*h;this.j=p;this.Jc=c;this.va=b;this.C=this.Da("captions-text");this.hc=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.Sa=mfb(d,e,f,h);this.Kc=m;l&&(this.D=this.Da("caption-edit"),this.S(this.D,"click",function(){F.Kc()}));
this.type=0;this.ib=this.Sa*nfb(q);a=new g.iT(this.element,!0);g.D(this,a);a.subscribe("dragstart",this.RZ,this);a.subscribe("dragmove",this.QZ,this);a.subscribe("dragend",this.PZ,this);this.tb=this.kb=this.Wb=this.Mb=0;a="";this.j.windowOpacity&&(a=afb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:!1===this.j.isVisible?"none":"","text-align":ofb[this.j.textAlign]};this.hc&&(b["border-radius"]=a?this.ib/8+"px":"");(this.B=2===this.u.params.oi||
3===this.u.params.oi)&&pfb(this,this.element);g.Lm(this.element,b);switch(this.j.Cl){case 0:case 1:case 2:g.Rp(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Rp(this.element,"ytp-caption-window-bottom")}},pfb=function(a,b){var c="vertical-rl";
1===a.j.BP&&(c="vertical-lr");g.mf&&(c="vertical-lr"===c?"tb-lr":"tb-rl");g.Lm(b,"-o-writing-mode",c);g.Lm(b,"-webkit-writing-mode",c);g.Lm(b,"writing-mode",c);g.Lm(b,"text-orientation","upright");g.Rp(b,"ytp-vertical-caption");3===a.u.params.oi&&(g.Lm(b,"text-orientation",""),g.Lm(b,"transform","rotate(180deg)"))},nfb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},qfb=function(a,b){var c={},d=b.background?b.background:a.j.Be.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Be.backgroundOpacity;d=afb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.hc&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ib/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Sa*nfb(b)+"px";d=1;e=b.color||a.j.Be.color;if(b.color||null!=b.textOpacity)e=afb(e),d=null==b.textOpacity?a.j.Be.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.LK&&(h=e=b.LK);var l=a.Sa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.bz()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Be.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.v4&&(c.visibility="hidden");1===b.CU&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.HK||g.FA,3===a.u.params.oi?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.En||2===b.En||3===b.En||4===b.En||5===b.En)if(g.HK)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.En){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},rfb=function(a){a.J=g.qf("SPAN");
g.Lm(a.J,{display:"block"});g.Rp(a.J,"caption-visual-line");a.C.appendChild(a.J)},sfb=function(a,b){var c=g.qf("SPAN");
g.Lm(c,{display:"inline-block","white-space":"pre-wrap"});g.Lm(c,qfb(a,b));c.classList.add("ytp-caption-segment");a.J.appendChild(c);c.previousElementSibling&&(g.Lm(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Lm(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},tfb=function(a,b,c){a.Ea=a.Ea||!!c;
var d={};Object.assign(d,a.j.Be);Object.assign(d,c||b.j);Object.assign(d,a.Jc.Be);(c=!a.J)&&rfb(a);for(var e=a.Ja&&a.La&&g.kd(d,a.La)?a.Ja:sfb(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(rfb(a),e=sfb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.rf(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.HK||!g.Nm(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Nm(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.Pc?g.Lm(e,m,"1em"):g.Lm(e,m,"0.5em")))}a.La=d;a.Ja=e;a.I.push(b)},mfb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>1.3*c&&(a=480),e=c/a*16);return e},h5=function(a,b,c,d){g.DT.call(this,a);
this.videoData=b;this.audioTrack=c;this.Va=d;this.C=b.IK},i5=function(a,b,c,d,e,f,h,l,m,n){g5.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},j5=function(a,b,c,d,e,f,h,l,m,n){g5.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.V=[];this.ea=this.Y=this.Ta=0;this.Aa=NaN;this.Tb=0;this.lc=null;this.Za=new g.Jp(this.v7,433,this);this.D&&(n.sb(this.D,this,167342),this.S(this.D,"click",function(){n.qb(p.D)}),a=new g.iT(this.element,!0),g.D(this,a),a.subscribe("hoverstart",function(){n.Ua(p.D,!0)},this));
g.Rp(this.element,"ytp-caption-window-rollup");g.D(this,this.Za);g.Lm(this.element,"overflow","hidden")},ufb=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.BP&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},vfb=function(a){a.V=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.Pq,c=0,d=0,e=a.V.length-1;c<b&&-1<e;){var f=a.V[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.V.length<b&&(d*=b/a.V.length);a.Y=d;b=Math;c=b.max;isNaN(a.Aa)&&((d=a.j.Kr)?(e=g.qf("SPAN"),g.Af(e,"\u2013".repeat(d)),g.Lm(e,qfb(a,a.j.Be)),a.C.appendChild(e),a.Aa=e.offsetWidth,a.C.removeChild(e)):a.Aa=0);d=a.C;a.ea=c.call(b,a.Aa,a.Tb,(a.B?d.offsetHeight:d.offsetWidth)+1)},wfb=function(a,b){vfb(a);
var c=a.V.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.Y-c;if(c!==a.Ta){var d=0<c&&0===a.Ta;b||isNaN(c)||d||(g.Rp(a.element,"ytp-rollup-mode"),g.Kp(a.Za));g.Lm(a.C,"transform",ufb(a,c));a.Ta=c}vfb(a)},k5=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.XD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},l5=function(a,b,c,d,e){g.XD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},xfb=function(a){var b="_"+m5++;
return new l5(0,0x8000000000000,0,b,a)},zfb=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Sf){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=yfb(l.textContent,n.textContent,p.textContent,f.textContent,h);return new k5(a,b,e,c,l,d,m)}switch(m.Sf){case 9:case 10:m.En=1;break;case 11:m.En=2;break;case 12:m.En=3;break;case 13:m.En=4;break;case 14:m.En=5}return new k5(a,b,e,c,l.textContent||"",d,m)},yfb=function(a,b,c,d,e){var f=g.bz(),h=
f?g.qf("DIV"):g.qf("RUBY"),l=g.qf("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.qf("DIV"):g.qf("RP");a.textContent=b;h.appendChild(a);b=f?g.qf("DIV"):g.qf("RT");b.textContent=c;h.appendChild(b);c=e.Sf;if(10===c||11===c||12===c||13===c||14===c)if(g.Lm(b,"text-emphasis-style","filled circle"),g.Lm(b,"text-emphasis-color","currentcolor"),g.Lm(b,"webkit-text-emphasis","filled circle"),11===e.Sf||13===e.Sf)g.Lm(b,"webkit-text-emphasis-position","under left"),g.Lm(b,"text-emphasis-position","under left");c=!0;if(4===e.Sf||7===e.Sf||12===e.Sf||
14===e.Sf)g.Lm(h,"ruby-position","over"),g.Lm(h,"-webkit-ruby-position","before");else if(5===e.Sf||6===e.Sf||11===e.Sf||13===e.Sf)g.Lm(h,"ruby-position","under"),g.Lm(h,"-webkit-ruby-position","after"),c=!1;e=f?g.qf("DIV"):g.qf("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Lm(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Lm(f,"display","none"),f=f.nextElementSibling,g.Lm(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Lm(h.lastElementChild,"display","none"),d?(g.Lm(h,"padding-top","0.6em"),g.Lm(f,"top","0")):(g.Lm(h,"padding-bottom","0.6em"),g.Lm(f,"bottom","0")));return h},n5=function(){g.C.apply(this,arguments)},o5=function(a){n5.call(this);
this.C=a;this.pens={};this.V={};this.Y={};this.D="_"+m5++;this.J={};this.B=this.j=null;this.I=!0},p5=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},q5=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},r5=function(a,b){a=p5(a,b);
return void 0!==a?a:null},t5=function(a,b){a=a.getAttribute(b);
if(null!=a)return s5.test(a),a},Afb=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Y[d]:a.C);a=r5(b,"mh");null!=a&&(c.kz=a);a=r5(b,"ju");null!=a&&(c.textAlign=a);a=r5(b,"pd");null!=a&&(c.oi=a);a=r5(b,"sd");null!=a&&(c.BP=a);a=t5(b,"wfc");null!=a&&(c.windowColor=a);b=p5(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},Bfb=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.V[d]);a=r5(b,"ap");null!=a&&(c.Cl=a);a=p5(b,"cc");null!=a&&(c.Kr=a);a=p5(b,"ah");null!=a&&(c.Jj=a);a=p5(b,"rc");null!=a&&(c.Pq=a);b=p5(b,"av");null!=b&&(c.Fn=b);return c},Cfb=function(a,b,c,d){var e={};
Object.assign(e,Bfb(a,b));Object.assign(e,Afb(a,b));d?g.kd(e,a.C)?(d=a.D,e=a.C):d="_"+m5++:d=b.getAttribute("id")||"_"+m5++;a=p5(b,"t")+c;b=p5(b,"d")||0x8000000000000;if(2===e.oi||3===e.oi)c=e.Pq,e.Pq=e.Kr,e.Kr=c;return new l5(a,b,0,d,e)},u5=function(a){n5.call(this);
this.I=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},v5=function(a){a=g.ze(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Dfb=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Pq=a);b=b.ccColCount;void 0!==b&&(f.Kr=b);if(2===f.oi||3===f.oi)b=f.Pq,f.Pq=f.Kr,f.Kr=b;return new l5(c,d,0,e,f)},Ffb=function(){this.B=this.time=this.mode=this.u=0;
this.C=new Efb(this);this.D=new Efb(this);this.j=[];this.clear()},Hfb=function(a,b,c){if(255===a&&255===b||!a&&!b)return{yu:a,
Gr:b,result:0};a=Gfb[a];b=Gfb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.Ce()&&c.Gr===d;if(d)return{yu:a,Gr:b,result:1}}else if(b&128&&1<=a&&31>=a)return{yu:a,Gr:b,result:2};return{yu:a,Gr:b,result:3}},Jfb=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,Ifb(a.C,b,c,d))},Kfb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.t(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?Jfb(a,d.KS,d.LS,b):1===d.type&&a.u&496&&Ifb(a.D,d.KS,d.LS,b);a.j.length=0},w5=function(){this.type=0},x5=function(){this.state=this.Gr=this.yu=0},Lfb=function(){this.timestamp=this.j=0},y5=function(a){this.D=a;
this.B=[];this.j=this.u=this.row=0;this.style=new w5;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new Lfb}},z5=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},Qfb=function(a,b){switch(a){case 0:return Mfb[(b&127)-32];
case 1:return Nfb[b&15];case 2:return Ofb[b&31];case 3:return Pfb[b&31]}return 0},A5=function(a){return a.B[a.row][a.u]},B5=function(a,b,c){2<=b&&1<a.u&&(--a.u,A5(a).j=0);
var d=A5(a);d.timestamp=a.D.time+0;d.j=Qfb(b,c);32>a.u&&a.u++},Rfb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},C5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},Sfb=function(a){a.row=0<a.j?a.j:1;
a.u=1;C5(a,0,15)},Tfb=function(a){this.B=a;
this.D=0;this.style=new w5;this.I=new y5(this.B);this.J=new y5(this.B);this.text=new y5(this.B);this.u=this.I;this.C=this.J;this.j=this.u},Ufb=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(z5(d,c),Sfb(a.u),Sfb(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(z5(d,c),C5(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},Vfb=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},Wfb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},Efb=function(a){this.j=a;
this.D=0;this.B=new Tfb(this.j);this.I=new Tfb(this.j);this.u=new x5;this.C=this.B},Ifb=function(a,b,c,d){a.u.update();
b=Hfb(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.yu;c=b.Gr;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&B5(a,0,b),c&96&&B5(a,0,c),0!==b&&0!==c&&3===a.style.type&&z5(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.yu=e,b.Gr=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.j.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;Rfb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));C5(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:B5(b.j,0,32);break a;case 48:57===c?(d=b.j,A5(d).j=0,32>d.u&&d.u++):B5(b.j,1,c&15)}break;case 2:c&32&&B5(b.j,2,c&31);break;case 3:c&32&&B5(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Vfb(b);
break;case 33:d=b.j;1<d.u&&(--d.u,A5(d).j=0);break;case 36:d=b.j;b=A5(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:Ufb(b,2,d);break;case 38:Ufb(b,3,d);break;case 39:Ufb(b,4,d);break;case 40:B5(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);Sfb(d);Wfb(b);break;case 43:Wfb(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:z5(a,d)}C5(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;z5(a,d);Rfb(a,b,b+1,a.j-1);C5(a,a.row,1)}break;case 46:C5(b.C,0,15);break;case 47:z5(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,Vfb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},Xfb=function(){},D5=function(a,b,c){this.trackData=a;
this.I=c;this.version=this.D=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},E5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},F5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},G5=function(a,b){n5.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new Ffb;this.j.u=1<<this.track},Zfb=function(a){if("string"===typeof a)return!1;
a=new D5(a,8,0);return Yfb(a)},Yfb=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==F5(a))return!1;
a.version=E5(a);if(1<a.version)return!1;E5(a);E5(a);E5(a);return!0},H5=function(){n5.call(this)},$fb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new k5(b,c,d,e.id,p.nodeValue,f||0<n,g.hd(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);$fb(a,b,c,d,e,!0,p,q,m)}}},agb=function(a){var b=a.split(":");
a=0;b=g.t(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},bgb=function(a,b,c,d){d=Object.assign({kz:0},d);
return new l5(a,b,c,"_"+m5++,d)},I5=function(a,b){g.C.call(this);
this.F=a;this.Z=b;this.parser=null;this.j=this.F.Cy()},igb=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.j&&b){var f=e,h=cgb(a,b,d),l=[];try{for(var m=g.t(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,r=p.rP;l="string"!==typeof q?l.concat(dgb(a,c,q,r,f)):"WEBVTT"===q.substring(0,6)?l.concat(egb(a,q,r)):l.concat(fgb(a,c,q,r))}var u=l}catch(x){g.CD(x),a.clear(),u=[]}if(0!==u.length)return u}b=ggb(b);if(!b)return[];try{return"string"!==typeof b?dgb(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?egb(a,b,d):fgb(a,c,b,d)}catch(x){return g.CD(x),a.clear(),[]}},ggb=function(a){if("string"===
typeof a||Zfb(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.kG(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.WF(a)},cgb=function(a,b,c){if("string"===typeof b||Zfb(b))return[{trackData:b,
rP:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.Cua(d);if(a.j&&e){var f=g.uua(e),h=g.vua(e);e=e.j;f&&e&&a.j.jE(e,f,h)}a=g.tG(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.WF(e),f.push({trackData:e,rP:c+1E3*h});jgb(d,f,c);return f=f.filter(function(l){return!!l.trackData})},jgb=function(a,b,c){var d=g.kG(a,0,1836476516),e=9E4;
d&&(e=g.lG(d)||9E4);d=0;for(var f=g.tG(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.kG(a,l.dataOffset,1953653094))&&(l=g.kG(a,l.dataOffset,1952867444))&&(l=g.rG(l)/e*1E3,0===h&&(d=l),b[h].rP=l-d+c||c*h*1E3)}},dgb=function(a,b,c,d,e){if(!Zfb(c))throw Error("Invalid binary caption track data");
a.parser||(a.parser=new G5(e,b));return a.parser.u(c,d)},egb=function(a,b,c){a.parser||(a.parser=new H5);
a=a.parser.u(b,c);.01>Math.random()&&g.DD(Error("Deprecated subtitles format in web player: WebVTT"));return a},fgb=function(a,b,c,d){if("{"===c[0])try{return a.parser||(a.parser=new u5(kgb(b))),a.parser.u(c,d)}catch(f){return g.CD(f),[]}var e=g.B8a(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.parser||(a.parser=new o5(kgb(b),a.Z)),a.parser.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},kgb=function(a){var b=
{};
if(a=g.aL(a))b.lang=a,g.C$a.test(a)&&(b.oi=1);return b},J5=function(a){g.AT.call(this,a);
var b=this;this.F=a;this.Z=this.F.T();this.videoData=this.F.getVideoData();this.tb=this.F.jb();this.B={Be:{}};this.D={Be:{}};this.Ea=[];this.ea={};this.Ta={};this.va=!1;this.hc=g.ZM(this.videoData);this.ib=g.YLa(this.videoData,this.F);this.Tb=!!this.videoData.captionTracks.length;this.lc=!!this.videoData.ke;this.Za="3"===this.Z.controlsType;this.u=this.J=this.V=this.Sa=this.kb=null;this.gb=new I5(this.F,this.Z);this.j=null;this.Aa=new g.cI(this);this.I=new g.T({G:"div",N:"ytp-caption-window-container",
X:{id:"ytp-caption-window-container"}});this.Y={top:0,right:0,bottom:0,left:0,width:1,height:1};var c=null,d=g.Mq("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.nq(d));this.storage=c;var e;this.Mb=!(null==(e=a.qe())||!e.dE());this.C=lgb(this);this.xa=!this.C&&this.Za&&this.Mb&&this.ib;g.D(this,this.gb);this.C?this.La=this.Ja=null:(this.Ja=new g.Hp(this.RP,void 0,this),g.D(this,this.Ja),this.La=new g.Jp(this.Y8,2E3,this),g.D(this,this.La));g.D(this,this.Aa);g.KS(this.player,this.I.element,
4);g.D(this,this.I);this.C||this.Aa.S(a,"resize",this.UP);(this.Wb=g.kK(this.Z)&&!g.Cz()&&!this.F.isFullscreen()&&!this.C&&!this.xa)&&this.Aa.S(a,"resize",this.F6);this.Aa.S(a,"onPlaybackAudioChange",this.T5);this.Aa.S(a,g.ZD("captions"),function(f){b.onCueRangeEnter(f)});
this.Aa.S(a,g.$D("captions"),function(f){b.onCueRangeExit(f)});
mgb(this,bfb()||{});this.player.Na("onCaptionsModuleAvailable")},pgb=function(a){if(1===a.Z.Mb||1===a.videoData.PC||"alwayson"===g.DM(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().u;if(2===a.Z.Mb){if(g.DK(a.Z))var c=ngb(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(null!=c)return!!c}c=Ueb(a.player.getAudioTrack(),g.DK(a.Z));var d=g.DM(a.videoData,"yt:cc");if(void 0===ogb(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===
b||"on"===g.DM(a.videoData,"yt:cc")},K5=function(a,b){if(a.j&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.j||"FORCED_ON"===a.u},ogb=function(a){var b=void 0,c=g.aA(g.$z(),65);
if(g.DK(a.Z)&&null!=c){if(null!=ngb(a))return!1;b=!c}return b},qgb=function(a){var b;
a.hc?b=new h5(a.Z,a.videoData,a.player.getAudioTrack(),a.player):a.ib?b=new f5(a.videoData.j,a.player):a.Tb?b=new g.ET(a.Z,a.videoData,a.player.getAudioTrack()):b=new g.GT(a.Z,a.videoData.ke,a.videoData.videoId,g.fAa(a.videoData),a.videoData.nm,a.videoData.eventId);return b},M5=function(a,b){if(a.u){if(a.J&&a.J.C)return a.J.C;
g.QM(a.videoData)&&(b=!0);b||(b=a.lc?!1:a.Tb?!1:!0);b=b||rgb(a);b=g.BT(a.u.j,b);var c=null;if(Veb(a.Z)){var d=a.F.isInline()?void 0:g.Uz("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.Z.captionsLanguagePreference,g.DM(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.aL(b[m])===l)return b[m];l=l.split("-")[0];for(m=0;m<b.length;m++)if(g.aL(b[m])===l)return b[m]}}if(a.Z.K("web_player_always_enable_auto_translation")&&
f&&a.u&&(e=a.u.C,e.length))for(e=g.t(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.Z.captionsLanguagePreference,g.DM(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.aL(b[f])===d[e])return b[f];d=null;a.J&&a.J.B&&(d=a.J.B);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||L5(a));d&&c&&(d=Web(d,c));return d}return null},L5=function(a){return a.J&&a.J.j},N5=function(a){var b=L5(a);
return!!b&&a.j===b},sgb=function(a){g.BT(a.u.j,!0);
var b=Ueb(a.player.getAudioTrack(),g.DK(a.Z)),c;"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=M5(a,a.va):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&K5(a)?c=L5(a):ogb(a)||a.va||pgb(a)?c=M5(a,a.va):K5(a)&&(c=L5(a));if(a.C||a.xa){var d=g.BT(a.u.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.qf("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.ZK(f));h.setAttribute("srclang",g.aL(f));h.setAttribute("id",f.toString());a.xa||h.setAttribute("src",a.u.Wu(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.F.qe();c.aB(b);c=c.ub();a.Mb&&a.Aa.S(c.textTracks,"change",a.d8)}else!a.j&&c&&O5(a,c),a.player.Na("onCaptionsTrackListChanged"),a.player.Na("onApiChange")},tgb=function(a,b){var c=a.F.qe().ub().textTracks;
a=a.j.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},O5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.va=c,a.va&&(g.DK(a.Z)?P5(a,!!b):Q5(a,!!b)));a.j=b;K5(a)&&(a.j=L5(a));a.load()},vgb=function(a,b){if(b instanceof l5){var c=a.ea[b.id];
c&&c.u!==b&&(c.dispose(),delete a.ea[b.id],c=null);c||(c=ugb(a,b))&&(a.ea[b.id]=c)}else c=b.windowId,a.Ta[c]||(a.Ta[c]=[]),a.Ta[c].push(b)},ugb=function(a,b){var c=wgb(a);
if(!c)return null;var d=a.j?g.aL(a.j):null;d&&g.C$a.test(d)&&(b.params.oi=1);var e=a.tb.getPlayerSize();d=e.height*a.Y.height;e=e.width*a.Y.width;"google-live"!==a.Z.playerStyle||a.B.isDefault||Object.assign(b.params,a.B);switch(null!=b.params.kz?b.params.kz:1<b.j.length?1:0){case 1:return new i5(b,a.B,a.D,c.width,c.height,e,d,a.Z.experiments,a.gJ.bind(a),a.F);case 2:return new j5(b,a.B,a.D,c.width,c.height,e,d,a.Z.experiments,a.gJ.bind(a),a.F);default:return new g5(b,a.B,a.D,c.width,c.height,e,d,
a.Z.experiments,a.gJ.bind(a),a.F)}},mgb=function(a,b,c){c=void 0===c?!1:c;
var d=R5.Be;a.B={};Object.assign(a.B,R5);a.B.Be={};Object.assign(a.B.Be,d);a.D={Be:{}};var e=b.backgroundOverride?a.D:a.B,f=b.background||d.background;s5.test(f);e.Be.background=f;e=b.colorOverride?a.D:a.B;f=b.color||d.color;s5.test(f);e.Be.color=f;e=b.windowColorOverride?a.D:a.B;f=b.windowColor||R5.windowColor;s5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Be.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.B;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Be.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Be;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.D:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Be.textOpacity=f;e=b.windowOpacityOverride?a.D:a.B;f=b.windowOpacity;null==f&&(f=R5.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.D:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Be.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Be.fontFamily=f;a.loaded&&a.UP();c&&g.Tz("yt-player-caption-display-settings",b,2592E3)},ygb=function(a,b,c){b&&!a.V?(b=xfb({oi:0,
lang:"ru"}),a.V=[b,new k5(b.start,b.end-b.start,0,b.id,null!=c?c:"\u0421\u0443\u0431\u0442\u0438\u0442\u0440\u044b \u0431\u0443\u0434\u0443\u0442 \u0432\u044b\u0433\u043b\u044f\u0434\u0435\u0442\u044c \u0442\u0430\u043a")],a.player.ye(a.V)):!b&&a.V&&(xgb(a,a.V),a.V=null)},xgb=function(a,b){a.player.Dh(b);
b=g.t(b);for(var c=b.next();!c.done;c=b.next())g.wb(a.Ea,c.value);g.Ip(a.Ja)},wgb=function(a){var b=a.tb.getVideoContentRect(!0).height,c=a.tb.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.Y.height;c*=a.Y.width;return{width:c,height:b}},Q5=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},P5=function(a,b){a.F.isInline()||g.Tz("yt-player-sticky-caption",b,2592E3)},ngb=function(a){if(!a.F.isInline())return g.Uz("yt-player-sticky-caption")},lgb=function(a){var b,c=!(null==(b=a.F.qe())||!b.cE());
return a.Za&&c&&!a.ib},rgb=function(a){return a.Z.K("web_deprecate_always_includes_asr_setting")&&g.DK(a.Z)?!0:!!g.aA(g.$z(),66)};
g.AW.prototype.OB=g.ca(40,function(a){var b=2;this.Za.has(a)?b=0:g.HRa(this,a)&&(b=1);return b});
g.yY.prototype.OB=g.ca(39,function(a){return this.jd.OB(a)});
g.AW.prototype.jE=g.ca(38,function(a,b,c){this.Ja.set(a,{Qr:b,XA:c})});
g.yY.prototype.jE=g.ca(37,function(a,b,c){this.jd.jE(a,b,c)});
g.DT.prototype.vO=g.ca(30,function(){return!1});
g.DT.prototype.Rs=g.ca(29,function(){});
g.ET.prototype.Rs=g.ca(28,function(a,b,c){var d=this;this.isDisposed();b=this.Wu(a,b);this.ir();this.u=g.Ly(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.GT.prototype.Rs=g.ca(27,function(a,b,c){var d=this;this.isDisposed();b=this.Wu(a,b);this.ir();this.u=g.Ly(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.nT.prototype.Tx=g.ca(26,function(){for(var a=g.Ye(document,"track",void 0,this.j),b=0;b<a.length;b++)g.xf(a[b])});
g.nW.prototype.Tx=g.ca(25,function(){this.mediaElement.Tx()});
g.nT.prototype.dE=g.ca(24,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.nW.prototype.dE=g.ca(23,function(){return this.mediaElement.dE()});
g.nT.prototype.cE=g.ca(22,function(){return!!this.j.textTracks});
g.nW.prototype.cE=g.ca(21,function(){return this.mediaElement.cE()});
g.nT.prototype.aB=g.ca(20,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.nW.prototype.aB=g.ca(19,function(a){this.mediaElement.aB(a)});
g.sY.prototype.eC=g.ca(9,function(){return this.I});
g.BZ.prototype.eC=g.ca(8,function(){var a;return(null==(a=g.nS(this))?void 0:a.Cy())||null});
g.xS.prototype.Cy=g.ca(7,function(){return this.app.eC()});
g.pZ.prototype.Cy=g.ca(6,function(){var a;return(null==(a=this.Ga)?void 0:a.eC())||null});
g.KF.prototype.cG=g.ca(2,function(a){return(a=this.Ho(a))?a.j:0});
g.zH.prototype.cG=g.ca(1,function(){return 0});
var $eb=/#(.)(.)(.)/,Zeb=/^#(?:[0-9a-f]{3}){1,2}$/i,gfb={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",
chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",
li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaq",
min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",
nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",
pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",
sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",
sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",
ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",
ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};e5.prototype.contains=function(a){a=g.Jb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
e5.prototype.length=function(){return this.segments.length/2};
g.w(dfb,g.C);g.k=dfb.prototype;g.k.oa=function(){g.C.prototype.oa.call(this);this.B&&this.B.cancel()};
g.k.sz=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Jd();var b=this.j;this.j=g.jb(this.Y.bq(a).fb);b!==this.j&&this.V&&this.V()};
g.k.reset=function(){this.C=new e5;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.mV=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Ar(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.OA(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai)if(b=this.player.Cy()){var c=a.fb[0].j.info.id,d=a.fb[0].Ma,e=a.fb[0].B;if(this.policy.Aa){if(b=b.Cs(e,d,c,3))a.J=b}else if(c=b.Fm(e,d,c,3))if(b=b.OB(d),0===b)c&&(a.u=new g.DF(c));else if(2===b){this.J.start();efb(this)&&this.seekTo(this.player.getCurrentTime());
return}}a.fb[0].duration?(this.C.contains(a.fb[0].Ma)||ffb(this,a),this.j=g.jb(a.fb)):efb(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.w(f5,g.DT);g.k=f5.prototype;g.k.Rs=function(a,b,c){var d=this;this.ir();b=ifb(this,a.getId());b||(b=a.languageCode,b=this.u.isManifestless?jfb(this,b,"386"):jfb(this,b));if(b){var e=1E3*(b.index.cG(b.index.Jm())-b.index.getStartTime(b.index.Jm())),f=new g.ELa(this.Z);this.B=new dfb(f,this.F,b,function(h,l){c(h,a,l,e)},this.I||g.vH(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.vO=function(){var a=this.D;this.D=!1;return a};
g.k.Yy=function(a){var b=this.I?[new g.YK({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.YK({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.u.isManifestless?hfb(this,"386"):hfb(this);b=g.t(b);for(var c=b.next();!c.done;c=b.next())g.CT(this.j,c.value);a()};
g.k.ir=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.Wu=function(){return""};
var s5=/^#(?:[0-9a-f]{3}){1,2}$/i,kfb=window.yt&&window.yt.msgs_||window.ytcfg&&window.ytcfg.msgs||{};g.Fa("yt.msgs_",kfb);var ofb=["left","right","center","justify"];g.w(g5,g.T);g.k=g5.prototype;g.k.RZ=function(a,b){this.kb=a;this.tb=b;var c=g.Um(this.element,this.element.parentElement);this.Mb=a-c.x;this.Wb=b-c.y};
g.k.QZ=function(a,b){if(a!==this.kb||b!==this.tb){g.Qp(this.element,"ytp-dragging")||g.Rp(this.element,"ytp-dragging");var c=g.Wm(this.element);a=a-this.Mb-.02*this.playerWidth;var d=b-this.Wb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.ze(e,0,2));var f=(d+c.height/2)/this.gb*3;f=Math.floor(g.ze(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.ze(a,0,1);c=(d+f/2*c.height)/this.gb;c=100*g.ze(c,0,1);this.u.params.Cl=b;this.u.params.Fn=c;this.u.params.Jj=a;this.u.params.isDefault=
!1;this.j.Cl=b;this.j.Fn=c;this.j.Jj=a;this.j.isDefault=!1;this.va.Cl=b;this.va.Fn=c;this.va.Jj=a;this.va.isDefault=!1;this.pX()}};
g.k.PZ=function(){g.Tp(this.element,"ytp-dragging")};
g.k.pX=function(){this.Vz(this.I)};
g.k.getType=function(){return this.type};
g.k.Vz=function(a){var b=Math.min(this.JT(),this.maxWidth),c=this.IT(),d="";3===this.u.params.oi&&(d="rotate(180deg)");g.Lm(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.rK(a);d={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.Jj+2,f=this.j.Cl;switch(f){case 0:case 3:case 6:(b=this.j.Be.fontSizeIncrement)&&0<b&&2!==this.j.oi&&3!==
this.j.oi&&(e=Math.max(e/(1+2*b),2));d.left=e+"%";break;case 1:case 4:case 7:d.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,d.width=b+"px",d["margin-left"]=b/-2+"px"):d.transform+=" translateX(-50%)";break;case 2:case 5:case 8:d.right=100-e+"%"}b=.96*this.j.Fn+2;switch(f){case 0:case 1:case 2:d.top=b+"%";break;case 3:case 4:case 5:d.top=b+"%";(c=c||this.element.clientHeight)?(d.height=c+"px",d["margin-top"]=c/-2+"px"):d.transform+=" translateY(-50%)";break;case 6:case 7:case 8:d.bottom=100-b+"%"}g.Lm(this.element,
d);if(this.D){c=this.C.offsetHeight;d=1;for(f=0;f<a.length;f++)b=a[f],"string"===typeof b.text&&(d+=b.text.split("\n").length-1,b.append||0===f||d++);c/=d;this.D.style.height=c+"px";this.D.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.rK=function(a){var b;for(b=0;b<a.length&&a[b]===this.I[b];b++);if(this.Ea||this.I.length>b)b=0,this.Ea=!1,this.I=[],this.J=this.La=this.Ja=null,g.tf(this.C);for(;b<a.length;b++)tfb(this,a[b])};
g.k.JT=function(){return 0};
g.k.IT=function(){return 0};
g.k.toString=function(){return g.T.prototype.toString.call(this)};g.w(h5,g.DT);h5.prototype.Rs=function(a,b,c){Yeb(this.videoData.videoId,a.vssId,c)};
h5.prototype.Yy=function(a){if(this.audioTrack)for(var b=g.t(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.CT(this.j,c.value);a()};g.w(i5,g5);i5.prototype.rK=function(a){var b=this.u.j;g5.prototype.rK.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,zgb);var e=c.j;var f=d}tfb(this,c,d)}};
var zgb={v4:!0};g.w(j5,g5);g.k=j5.prototype;g.k.pX=function(){g.Lp(this.Za)};
g.k.v7=function(){g.Tp(this.element,"ytp-rollup-mode");this.Vz(this.lc,!0)};
g.k.IT=function(){return this.B?this.ea:this.Y};
g.k.JT=function(){return this.B?this.Y:this.ea};
g.k.Vz=function(a,b){this.lc=a;if(this.u.params.Pq){for(var c=0,d=0;d<this.I.length&&c<a.length;d++)this.I[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.I.concat(a.slice(c)));this.Tb=this.ea;this.Y=this.ea=0;g5.prototype.Vz.call(this,a);wfb(this,b)}g5.prototype.Vz.call(this,a)};g.w(k5,g.XD);k5.prototype.toString=function(){return g.XD.prototype.toString.call(this)};g.w(l5,g.XD);l5.prototype.toString=function(){return g.XD.prototype.toString.call(this)};
var m5=0;g.w(n5,g.C);n5.prototype.u=function(){return[]};
n5.prototype.reset=function(){};g.w(o5,n5);o5.prototype.reset=function(){this.J={};this.B=this.j=null;this.I=!0};
o5.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.t(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.t(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=q5(a,"b");
null!=l&&(h.bold=l);l=q5(a,"i");null!=l&&(h.italic=l);l=q5(a,"u");null!=l&&(h.underline=l);l=r5(a,"et");null!=l&&(h.charEdgeStyle=l);l=r5(a,"of");null!=l&&(h.offset=l);l=t5(a,"bc");null!=l&&(h.background=l);l=t5(a,"ec");null!=l&&(h.LK=l);l=t5(a,"fc");null!=l&&(h.color=l);l=r5(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=p5(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=p5(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=p5(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=r5(a,"rb");null!=l&&10!==l&&
0!==l&&(h.Sf=10<l?l-1:l);a=r5(a,"hg");null!=a&&(h.CU=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Y[c]=Afb(this,a);break;case "wp":c=a.getAttribute("id"),this.V[c]=Bfb(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.t(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=Cfb(this,a,b,!1);(a=this.J[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.J[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;
h=!!q5(a,"a");l=(p5(a,"t")||0)+l;var m=p5(a,"d")||5E3;h||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.I=null!=a.getAttribute("d"));for(var r=0;r<q.length;r++){var u=q[r],x=void 0;0<r&&(h=!0);var z=void 0;1===u.nodeType&&(z=u);if(z&&"s"===z.tagName){if((u=(u=z.getAttribute("p"))?this.pens[u]:null)&&u.Sf&&(1===u.Sf?(u=q.slice(r,r+
4),4===u.length&&(x=zfb(l,m,f,h,n,u,this.pens),r+=3)):x=zfb(l,m,f,h,n,[z],this.pens)),!x){var B=z;x=l;z=m;u=f;var F=h,G=n,E=B.textContent?B.textContent:"",L=B.getAttribute("p");L=L?this.pens[L]:null;B=p5(B,"t")||0;x=new k5(x+B,z-B,G,u,E,F,L)}}else x=new k5(l,m,n,f,u.textContent||"",h,p);c.push(x);this.B=x}if(0<c.length)for(c[0].windowId===this.D&&(this.j=Cfb(this,a,b,!0),d.push(this.j)),a=g.t(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var Agb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(u5,n5);u5.prototype.reset=function(){this.B.clear()};
u5.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.t(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.LK=v5(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=v5(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=v5(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Sf=10<h?h-1:h,f.En=Agb.get(f.Sf));e.hgHorizGroup&&(f.CU=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.t(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.kz=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.oi=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.BP=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=v5(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.t(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.Jj=e.ahHorPos),void 0!==e.apPoint&&(f.Cl=e.apPoint),void 0!==e.avVerPos&&(f.Fn=e.avVerPos),void 0!==e.ccCols&&(f.Kr=e.ccCols),void 0!==e.rcRows&&(f.Pq=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.t(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=Dfb(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+m5++,h=Dfb(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var r=p[l],u=r.utf8;if(u){var x=r.tOffsetMs||0,z=null;r.pPenId&&(z=this.j.get(r.pPenId));if(2===(null!=h.params.kz?h.params.kz:1<h.j.length?1:0)&&m&&"\n"===u)continue;if(r=z&&1===z.Sf)if(r=l,r+3>=p.length||!p[r+1].pPenId||!p[r+2].pPenId||!p[r+3].pPenId)r=!1;else{var B=p[r+1].pPenId;(B=this.j.get(B))&&B.Sf&&2===B.Sf?(B=p[r+2].pPenId,B=this.j.get(B),!B||!B.Sf||3>B.Sf?r=!1:(B=p[r+3].pPenId,r=(B=this.j.get(B))&&
B.Sf&&2===B.Sf?!0:!1)):r=!1}if(r){x=p[l+1].utf8;r=p[l+3].utf8;B=p[l+2].utf8;var F=this.j.get(p[l+2].pPenId);u=yfb(u,x,B,r,F);m=new k5(d,e,n,f,u,m,z);l+=3}else m=new k5(d+x,e-x,n,h.id,u,m,z||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};Ffb.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
Ffb.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var Gfb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];w5.prototype.set=function(a){this.type=a};
w5.prototype.get=function(){return this.type};
x5.prototype.clear=function(){this.state=0};
x5.prototype.update=function(){this.state=2===this.state?1:0};
x5.prototype.Ce=function(){return 0!==this.state};
x5.prototype.matches=function(a,b){return this.Ce()&&a===this.yu&&b===this.Gr};
Lfb.prototype.reset=function(){this.timestamp=this.j=0};
y5.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
y5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
y5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var Mfb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Nfb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Ofb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Pfb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Tfb.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.I;this.C=this.J;this.j=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
Efb.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};Xfb.prototype.C=function(){};g.w(D5,Xfb);D5.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+m5++;c=c/1E3-this.I;d=d/1E3-this.I;a=new l5(c,d-c,5,f,{textAlign:0,Cl:0,Jj:2.5*b,Fn:5.33*a});e=new k5(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.w(G5,n5);G5.prototype.u=function(a){a=new D5(a,a.byteLength,this.B);if(Yfb(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=F5(a)*(1E3/45):1===a.version&&(a.B=4294967296*F5(a)+F5(a)),a.D=E5(a);0<a.D;a.D--){var b=E5(a),c=E5(a),d=E5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,KS:c,LS:d,order:b.j.length}))}Kfb(this.j,a);return a.u}return[]};
G5.prototype.reset=function(){this.j.clear()};g.w(H5,n5);
H5.prototype.u=function(a,b){var c=[];a=a.split(Bgb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!Cgb.test(e)){var h=Dgb.exec(e);if(h&&4<=h.length){var l=agb(h[1]),m=agb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,u="";n=g.t(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var z=x[1];switch(x[0]){case "line":x=z.split(",");x[0].endsWith("%")&&(p=x[0],h.Fn=Number.parseInt(p,10),2===x.length&&(q=x[1].trim()));break;case "position":x=
z.split(",");r=x[0];h.Jj=Number.parseInt(r,10);2===x.length&&(u=x[1].trim());break;case "align":switch(z){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.Jj=0;break;case 1:h.Jj=100;break;case 2:h.Jj=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(u){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.Cl=q}e=e.substring(Dgb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=bgb(l,m,5,u),m=new k5(l,m,5,f.id,h,!1,g.hd(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(Egb),1===q.length?(h=5,u=bgb(l,m,h,u)):(p=h=6,u=Object.assign({Kr:32},u),u=new l5(l,m,p,"_"+m5++,u)),c.push(u),p=l,r=0;r<q.length;r++)n=q[r],0===r%2?(x=g.B8a("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(z=x.createElement("span"),z.appendChild(x.createTextNode(n))):z=x.firstChild,$fb(this,p,m-(p-l),h,u,0<r,z,e,c)):p=agb(n)+f}Dgb.lastIndex=0}}return c};
var Cgb=/^NOTE/,Bgb=/(?:\r\n|\r|\n){2,}/,Dgb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Egb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.oW.ev(H5,{u:"wvppt"});g.w(I5,g.C);I5.prototype.clear=function(){this.parser&&this.parser.dispose();this.parser=null};
I5.prototype.reset=function(){this.parser&&this.parser.reset()};
I5.prototype.oa=function(){g.C.prototype.oa.call(this);this.clear()};var R5={windowColor:"#080808",windowOpacity:0,textAlign:2,Cl:7,Jj:50,Fn:100,isDefault:!0,Be:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(J5,g.AT);g.k=J5.prototype;g.k.oa=function(){if(this.C||this.xa){var a=this.F.qe();a&&!a.isDisposed()&&a.Tx()}else ygb(this,!1);g.AT.prototype.oa.call(this)};
g.k.lw=function(){if(this.Za)return this.C||this.xa;var a=Ueb(this.player.getAudioTrack(),g.DK(this.Z));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?K5(this):ogb(this)||K5(this)?!0:pgb(this)};
g.k.load=function(){var a=this;g.AT.prototype.load.call(this);this.J=this.player.getAudioTrack();this.u?this.j&&(this.gb.clear(),this.C?tgb(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Rs(this.j,"json3",function(b,c,d,e){if(b){a.Z.K("html5_modify_caption_vss_logging")&&(a.videoData.Pw=a.j||void 0);a.u.vO()&&(a.Ea=[],a.F.If("captions"),g.Ip(a.Ja),a.gb.reset());b=igb(a.gb,b,c,d,e);a.player.ye(b,void 0,a.ib);if(!(!a.va||a.xa||N5(a)||g.tK(a.Z)||g.mK(a.Z)||g.nK(a.Z)||"shortspage"===a.Z.Ea||
a.player.isInline())){g.Mp(a.La);b=xfb({Cl:0,Jj:5,Fn:5,Pq:2,textAlign:0,oi:0,lang:"ru"});a.Sa=[b];d=["\u0414\u043b\u044f \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u043d\u0430\u0436\u043c\u0438\u0442\u0435 \u043d\u0430 \u0437\u043d\u0430\u0447\u043e\u043a ",""];a.kb||(e=new g.XP(g.pQ()),g.D(a,e),a.kb=e.element);e=b.end-b.start;var f=g.ZK(a.j);f&&a.Sa.push(new k5(b.start,e,0,b.id,f));a.Sa.push(new k5(b.start,e,0,b.id,d[0]),new k5(b.start,e,0,b.id,a.kb,!0),new k5(b.start,e,0,b.id,d[1],
!0));a.player.ye(a.Sa);g.Kp(a.La)}!a.va||a.xa||N5(a)||(g.DK(a.Z)?P5(a,!0):Q5(a,!0),a.J&&(a.J.C=a.j),a.player.jr());var h;null==(h=a.F.Nc())||h.ya("cc",{kind:c.kind});a.va=!1}}),this.C||this.xa||N5(this)||this.player.Na("captionschanged",g.$K(this.j))):(this.u=qgb(this),g.D(this,this.u),this.u.Yy(function(){sgb(a)}))};
g.k.unload=function(){this.C&&this.j?tgb(this,!1):(this.La&&g.Mp(this.La),this.player.If("captions"),this.Ea=[],this.u&&this.u.ir(),this.gb.clear(),this.V&&this.player.ye(this.V),this.UP());g.AT.prototype.unload.call(this);this.player.jr();this.player.Na("captionschanged",{})};
g.k.create=function(){this.lw()&&this.load();var a;a:{var b,c,d;if(this.Z.K("suggest_caption_correction_menu_item")&&this.Z.K("web_player_nitrate_promo_tooltip")&&(null==(b=this.videoData.getPlayerResponse())?0:null==(c=b.captions)?0:null==(d=c.playerCaptionsTracklistRenderer)?0:d.openTranscriptCommand)){var e,f;if(b=null==(a=this.videoData.getPlayerResponse())?void 0:null==(e=a.captions)?void 0:null==(f=e.playerCaptionsTracklistRenderer)?void 0:f.captionTracks)for(a=g.t(b),e=a.next();!e.done;e=a.next())if(e=
e.value,"asr"===e.kind&&"en"===e.languageCode){a=!0;break a}}a=!1}a&&this.F.ma("showpromotooltip",this.I.element)};
g.k.d8=function(){for(var a=this.F.qe().ub().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=g.BT(this.u.j,!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.j:null)!==b&&O5(this,b,!0)};
g.k.b$=function(){!this.j&&this.C||this.unload()};
g.k.onCueRangeEnter=function(a){this.Ea.push(a);g.Ip(this.Ja)};
g.k.onCueRangeExit=function(a){g.wb(this.Ea,a);this.u instanceof f5&&this.u.I&&this.player.Dh([a]);g.Ip(this.Ja)};
g.k.getCaptionWindowContainerId=function(){return this.I.element.id};
g.k.Y8=function(){xgb(this,this.Sa);this.Sa=null};
g.k.RP=function(){var a=this;if(!this.Wb||!this.C){this.Ja.stop();g.gba(this.Ta);this.Ea.sort(g.YD);var b=this.Ea;if(this.V){var c=g.Vn(b,function(f){return-1===this.V.indexOf(f)},this);
c.length&&(b=c)}b=g.t(b);for(c=b.next();!c.done;c=b.next())vgb(this,c.value);b={};c=g.t(Object.entries(this.ea));for(var d=c.next();!d.done;b={Vt:b.Vt,lm:b.lm},d=c.next()){var e=g.t(d.value);d=e.next().value;e=e.next().value;b.Vt=d;b.lm=e;this.Ta[b.Vt]?(b.lm.element.parentNode||(b.lm instanceof j5||b.lm instanceof i5||g.Wc(this.ea,function(f){return function(h,l){l!==f.Vt&&h.u.params.Cl===f.lm.u.params.Cl&&h.u.params.Jj===f.lm.u.params.Jj&&h.u.params.Fn===f.lm.u.params.Fn&&(h.dispose(),delete a.ea[l]);
return l===f.Vt}}(b),this),this.I.element.appendChild(b.lm.element)),b.lm.Vz(this.Ta[b.Vt])):(b.lm.dispose(),delete this.ea[b.Vt])}}};
g.k.d9=function(){mgb(this,{},!0);this.player.Na("captionssettingschanged")};
g.k.N3=function(){var a=R5.Be;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:R5.windowColor,windowOpacity:R5.windowOpacity};var b=bfb()||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.GY=function(a,b){var c={};Object.assign(c,bfb());Object.assign(c,a);mgb(this,c,b);this.player.Na("captionssettingschanged")};
g.k.UP=function(){!this.C&&this.loaded&&(g.Tc(this.ea,function(a,b){a.dispose();delete this.ea[b]},this),this.RP())};
g.k.rh=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.ze(b,-2,4);this.GY({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&O5(this,this.j,!0);break;case "stickyLoading":void 0!==b&&this.Z.I&&(g.DK(this.Z)?P5(this,!!b):Q5(this,!!b));break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Ja(b))break;if(g.hd(b)){O5(this,null,!0);break}a=g.BT(this.u.j,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||
this.Z.K("html5_enable_caption_changes_for_mosaic")&&(e.captionId||"")!==(b.captionId||""))||(c=b.translationLanguage?Web(e,b.translationLanguage):e)}this.uI(b.position);!c||c===this.j&&this.loaded||(a=g.VI(),b=g.aL(c),a.length&&b===a[a.length-1]||(a.push(b),g.Tz("yt-player-caption-language-preferences",a)),(a=Veb(this.Z))&&!this.F.isInline()&&g.Tz("yt-player-caption-sticky-language",b,86400*a),O5(this,c,!0))}else return this.loaded&&this.j&&!N5(this)?g.$K(this.j):{};return"";case "tracklist":return this.u?
g.hi(g.BT(this.u.j,!(!b||!b.includeAsr)),function(f){return g.$K(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.C||void 0===b||ygb(this,!!b);break;case "sampleSubtitlesCustomized":this.C||ygb(this,!!b,b);break;case "recommendedTranslationLanguages":return g.VI()}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Z.I&&a.push("stickyLoading");return a};
g.k.eq=function(){var a=this.j;this.Z.K("html5_modify_caption_vss_logging")&&(a=this.videoData.Pw||null);if(a){var b=a.vssId;a.translationLanguage&&b&&(b="t"+b+"."+g.aL(a));return{cc:b}}return{}};
g.k.P9=function(){this.isSubtitlesOn()?(g.DK(this.Z)?P5(this,!1):Q5(this,!1),this.Z.K("html5_modify_caption_vss_logging")&&(this.videoData.Pw=void 0),this.unload(),K5(this,!0)&&O5(this,L5(this),!1)):this.kY()};
g.k.kY=function(){this.isSubtitlesOn()||O5(this,N5(this)||!this.j?M5(this,!0):this.j,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.j&&!N5(this)};
g.k.T5=function(){var a=N5(this);K5(this,a)?O5(this,this.player.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.lw()&&(a?O5(this,M5(this),!1):this.load()))};
g.k.uI=function(a){a&&(this.Y={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.I.element.style.top=100*this.Y.top+"%",this.I.element.style.left=100*this.Y.left+"%",this.I.element.style.width=100*this.Y.width+"%",this.I.element.style.height=100*this.Y.height+"%",this.Z.K("html5_enable_caption_changes_for_mosaic")&&(this.I.element.style.position="absolute",a=wgb(this)))&&(this.I.element.style.width=a.width+"px",this.I.element.style.height=a.height+
"px")};
g.k.F6=function(){var a=this.F.qe();a&&!a.isDisposed()&&a.Tx();this.F.isFullscreen()?(this.C=this.Za=!0,this.loaded&&sgb(this)):(this.Za="3"===this.Z.controlsType,this.C=lgb(this));O5(this,this.j)};
g.k.gJ=function(){var a,b,c,d=null==(a=this.videoData.getPlayerResponse())?void 0:null==(b=a.captions)?void 0:null==(c=b.playerCaptionsTracklistRenderer)?void 0:c.openTranscriptCommand;d&&this.player.Na("innertubeCommand",d)};
g.oW.ev(J5,{RP:"smucd"});g.zT("captions",J5);})(_yt_player);
